- How to Use GitHub for AREDN.md
- README.md
update to new aredn repo (from aredn_ar71xx)
> update to new repo paths

- .circleci/config.yml
maximize number of processors in build
move larget transient files to new volume on otis
> build: testing new build scripts

- openwrt.mk
testing on ubnt nanostation xw
> aredn: upgrade to Openwrt 19.07.6

- files/etc/uci-defaults/45_aredn_reset_paths
> bugfix: reset download paths upon upgrade to default

- files/www/cgi-bin/advancedconfig
deletes AREDN and local alert messages immediately from the node
> feature: add advanced config option to purge AREDN Alert msgs

- files/etc/uci-defaults/45_aredn_reset_paths
merge issues with prior PR.  resubmitting.
> bugfix: re-submit path reset2 (previously approved)

- files/usr/lib/lua/aredn/info.lua
- files/www/cgi-bin/sysinfo.json
> feature: add mesh gateway setting to sysinfo.json

- files/www/cgi-bin/advancedconfig
Change _Advanced Configuration_ **EXECUTE** button value string to 
"Click EXECUTE button to trigger this action"
> feature: Execute Button Description

- files/usr/local/bin/snrlog
- files/www/cgi-bin/sysinfo.json
Fix typo (nill to nil) in pidfile test.
> bug: fix nill typo

- Makefile
- README.md
- config.mk
- feeds.conf
> aredn: Prepare the 3.21.4.0 release

- files/usr/lib/lua/aredn/info.lua
- files/www/cgi-bin/api
correct bug in info.lua library when there is no internet gateway accessible
> Lua info gateway

- files/www/cgi-bin/api
> bugfix: fix api when meshrf is disabled

- files/usr/lib/lua/aredn/info.lua
remove "GHz" label
returns as MHz value (ie. 2402)
> api enhancement: convert getFreq to use lib-iwinfo

- files/usr/lib/lua/aredn/info.lua
Read the entire local_message file rather than just the first line.
> fix: Local Alert File Read All

- files/usr/lib/lua/aredn/info.lua
Add a connection type field to **info.lua** so the **api** can provide it to the newui _Local Hosts_ display.
> Add LocalHost Connection Type

- files/usr/lib/lua/aredn/info.lua
- files/usr/lib/lua/aredn/olsr.lua
- files/usr/lib/lua/aredn/utils.lua
- files/www/cgi-bin/api
add support for estimated_throughput to api
> Api use libiwinfo frequency

- files/usr/lib/lua/aredn/info.lua
- files/usr/lib/lua/aredn/olsr.lua
- files/usr/lib/lua/aredn/utils.lua
- files/www/cgi-bin/api
traceroute, remotenodes to api
> add traceroute and remotenodes to api

- files/usr/lib/lua/aredn/info.lua
- files/usr/lib/lua/aredn/olsr.lua
- files/usr/lib/lua/aredn/utils.lua
Revise getLocalHosts() so it doesn't report unwanted hosts.  
getLocalCnxType() is no longer needed.
> api: revise localhost function

- files/www/cgi-bin/api
one-liner to sort remoteNodes by ascending ETX value for newui.
> api: sort remote nodes

- files/www/cgi-bin/vpn
- files/www/cgi-bin/vpnc
fixes #11
also fixes: https://www.arednmesh.org/comment/7412#comment-7412
(which has been hanging around for um... _years_!!) :facepalm:
> aredn: fix long node names for tunnels.

- files/www/cgi-bin/api
Ensure that Current Neighbor nodes are eliminated from the Remote Nodes list.
> api: fix remote nodes list

- files/usr/lib/lua/aredn/info.lua
- files/usr/lib/lua/aredn/uci.lua
- files/usr/lib/lua/aredn/utils.lua
- files/www/cgi-bin/api
add the node's tactical name to the sysinfo block
> Api add tactical name

- files/www/cgi-bin/perlfunc.pm
> aredn: add new ubnt Rocket M with USB device

- files/www/cgi-bin/mesh
Collecting bug fixes for the meshoween changes:
1. Create the meshstatus uci section on first-use as it won't exist.
> Meshoween: Bug fixes

- CONTRIBUTORS
- files/etc/uci-defaults/97_aredn_setup_meshstatus
- files/www/cgi-bin/mesh
> Meshoween: Better way to add new uci meshstatus section

- files/usr/local/bin/olsrd-config
This didn't work, so revert it. The actual fix will need to be in OLSR itself.
> Revert failed olsrd fix

- files/etc/config.mesh/aredn
- files/www/cgi-bin/setup
- files/www/cgi-bin/status
fix issue of lat/lon clearing after a Save Settings.
> fix: duplicate to the config.mesh structure after saving.

- files/www/cgi-bin/api
Prevent unauthenticated remote code execution as root in the 'traceroute' function. This could probably be improved, or the function removed entirely, or to apiprotected. This affects all nightly/custom builds since June when this function was added.
> bugfix: api traceroute function hardening

- Makefile
- files/www/cgi-bin/admin
that previously removed the -squashfs- portion to accommodate the OFS tool
> undo the renaming of output files

- .circleci/config.yml
move up from medium to large resource type for builds
> build: change to large resource type

- .circleci/config.yml
> Build timeout

- files/etc/config.mesh/aredn
- files/etc/hotplug.d/iface/11-meshrouting
- files/etc/uci-defaults/10_dmz_mode_migrate
- files/usr/local/bin/mesh-firewall
- files/usr/local/bin/node-setup
- files/usr/local/bin/olsrd-config
- files/usr/local/bin/vtun_up
- files/www/cgi-bin/ports
Migration dmz info to uci proper.
https://github.com/aredn/aredn/issues/167
> Dmz mode migrate fix

- files/www/cgi-bin/mesh
Change the way location is retrieved in the mesh page to the same as the status page
https://github.com/aredn/aredn/issues/196
> Fix missing location

- files/www/cgi-bin/admin
remove marginally effective filename devicetype checks.
> bugfix: remove filename checks for firmware uploads

- Makefile
- README.md
- config.mk
- feeds.conf
Return main branch to Nightly Builds
> Revert "aredn: Prepare the 3.22.1.0 release (#200)"

- files/usr/lib/lua/aredn/html.lua
Now ignore empty alerts.
https://github.com/aredn/aredn/issues/206
> Fix Issue #206 - Displaying empty alerts

- files/www/cgi-bin/mesh
Fix local service layout (missing piece of markup)
https://github.com/aredn/aredn/issues/205
> Fix issue #205 - Bad local service layout

- files/usr/lib/lua/aredn/html.lua
sysinfo.lua doesn't exist, correct path should just be sysinfo. Tested
> Fix sysinfo link

- files/www/cgi-bin/advancedconfig
- files/www/cgi-bin/advancedconfig.pl
New lua version of this page. The old page has been renamed with .pl extension
> Migrate advancedconfig page to lua

- files/www/cgi-bin/vpn
fixes #218
My ide likes to remove extraneous blanks, but the only functional change to the file is on line 461 where "target='_blank'" has been added.
> vpn send details in new browser window fixes #218

- files/usr/local/bin/mgr/rssi_monitor.lua
https://github.com/aredn/aredn/issues/224
> Fix typo when checking for multiple antennas

- files/www/cgi-bin/setup.pl
Fix submit to return to .pl page.
> Submit on setup.pl should return to setup.pl

- files/usr/lib/lua/aredn/hardware.lua
Fix for https://github.com/aredn/aredn/issues/223
> Add the interface guessing code like there is in perl

- files/usr/local/bin/node-setup
Was assuming certain files existed and, if not, node-setup would fail.
https://github.com/aredn/aredn/issues/233
Possibly https://github.com/aredn/aredn/issues/223
> Check for various service and port files before opening them

- files/www/cgi-bin/advancedconfig
Reboot on advancedconfig page was broken in a similar way to reboot on the setup page.
> Fix broken reboot on advancedconfig page

- files/etc/local/mesh-firewall/60-block-lan-across-wan
> Revert "Prevent mesh from accessing internal LAN"

- files/usr/local/bin/uploadctlservices
This service was absorbed by the lua manager
> Dont stop linkled service which no longer exists

- files/www/cgi-bin/setup
Was incorrectly treating blank lat/lon as valid coordinates ("" is true in lua, but false in perl)
> Fix map when lat/lon unknown

- files/www/cgi-bin/ports
- files/www/cgi-bin/ports.pl
Lua version of the 'ports' page
> Lua userpages: ports

- files/www/cgi-bin/setup
Timezones not being updated correctly
> Fix timezone management

- files/www/cgi-bin/setup
> Fix WAN IP check (check was inverted)

- files/www/cgi-bin/mesh
Missing + in pattern
https://github.com/aredn/aredn/issues/249
> Fix noprop color (typo in pattern match)

- files/www/cgi-bin/setup
Typo when setting power using iw command
https://github.com/aredn/aredn/issues/249
> tx power => txpower (typo)

- files/www/cgi-bin/advancedconfig
remove "trunk" from the urlprefix on advancedconfig line 71.  Fixes #260
> remove trunk from urlprefix

- files/usr/lib/lua/aredn/hardware.lua
- files/www/cgi-bin/setup
This was not correctly falling back onto the /etc/radios.json value if
the 'iw' didn't provide a value. Fixed and move to library.
> Fix wifi power offset calculation.

- files/www/cgi-bin/setup
Perl code was modified to handle channels -3 and -4.
Propagate this chance to Lua code.
(original fix https://github.com/aredn/aredn/pull/210)
> Add channel -3 & -4 (from original fix #210)

- files/www/cgi-bin/advancedconfig
- files/www/cgi-bin/setup
https://github.com/aredn/aredn/issues/267
> Fix mis-reporting of changed LAN subnet on reboot

- files/usr/local/bin/olsrd-config
- files/usr/local/bin/olsrd-config.pl
- files/www/cgi-bin/vpn
- files/www/cgi-bin/vpn.pl
- files/www/cgi-bin/vpnc
- files/www/cgi-bin/vpnc.pl
For discussion: I'm proposing the tunnels go next (the server and client pages together)
> Lua userpages: Tunnels

- files/usr/local/bin/nvram-setup
- files/usr/local/bin/nvram-setup.pl
- files/usr/local/bin/setpasswd
- files/usr/local/bin/setpasswd.pl
- files/usr/local/bin/wscan
- files/usr/local/bin/wscan.pl
- files/www/cgi-bin/fwinfo
- files/www/cgi-bin/fwinfo.pl
- files/www/cgi-bin/supporttool
- files/www/cgi-bin/supporttool.pl
- files/www/cgi-bin/sysinfo
- files/www/cgi-bin/sysinfo.pl
This replaces a few minor pages, as well as some perl scripts.
> Lua stragglers

- files/www/cgi-bin/vpn
Tunnel server was working but  check for displaying active status was using the wrong value.
> Fix active tunnel indicator for tunnel server

- files/usr/local/bin/olsrd-config
> Fix the pattern used to validate services

- files/www/cgi-bin/scan
> Fix broken wifi sorting

- files/usr/local/bin/olsrd-config
https://github.com/aredn/aredn/issues/282
> Fix noprop flag detection

- files/usr/local/bin/node-setup
Create file it it doesn't exist, but don't truncate it.
> Dont truncate aliases on upgrade

- files/www/cgi-bin/vpn
- files/www/cgi-bin/vpnc
Fix for https://github.com/aredn/aredn/issues/311
> Add @ back in as a valid password character

- files/www/cgi-bin/advancedconfig
Add an option (for firewall settings in the vtund app) to block/unblock tunnel traffic from going across the mesh. You probably never want tunnel traffic across the mesh, and this can happen accidentally if a tunnel node's WAN network is down.
> advancedconfig: tun wan only

- files/usr/local/bin/node-setup
Pass number to function not string
https://github.com/aredn/aredn/issues/313
> Fix wifi channel type

- files/www/cgi-bin/setup
Missing hidden variable caused Bad Gateway when switching to NAT mode
> Fix bad gateway when switching to LAN NAT mode

- files/www/cgi-bin/api
Remove the nested loops O(n^2) and replace with linear loops and hash tables O(2n).
> Optimize getRemoteNodes

- README.md
- files/www/help.html
Open to better wording so feel free to make suggestions.
> Update docs for VLAN change

- openwrt.mk
- patches/001-add_support_for_TP-Link_ATH79_CPE210_v1.patch
- patches/001-add_support_for_TP-Link_ATH79_CPE220_v2.patch
- patches/001-add_support_for_TP-Link_ATH79_CPE510_v1.patch
- patches/001-add_support_for_TP-Link_ATH79_CPE510_v2_v3.patch
- patches/001-add_support_for_TP-Link_ATH79_CPE610_v1.patch
- patches/001-add_support_for_TP-Link_ATH79_CPE610_v2.patch
- patches/001-add_support_for_TP-Link_ATH79_WBS210_v1.patch
- patches/001-add_support_for_TP-Link_ATH79_WBS210_v2.patch
- patches/001-add_support_for_TP-Link_ATH79_WBS510_v1.patch
- patches/001-add_support_for_TP-Link_ATH79_WBS510_v2.patch
- patches/001-add_support_for_TP-Link_CPE220_v2.patch
- patches/001-add_support_for_TP-Link_CPE220_v3.patch
- patches/001-add_support_for_TP-Link_CPE510_v3.20.patch
- patches/001-add_support_for_TP-Link_CPE510_v3.patch
- patches/001-add_support_for_TP-Link_CPE610_v1.patch
- patches/001-add_support_for_TP-Link_WBS510_v2.patch
- patches/001-ath79-cpe220v3-sysupgrade-supported.patch
- patches/001_cpe220v3_bugfix.patch
- patches/004-add-ldf-5nd.patch
- patches/004-add-lhg-5hpnd-xl.patch
- patches/006-add-lhg-5hpnd.patch
- patches/009-add-sxtsq.patch
- patches/700-cpe-diags.patch
- patches/704-enable-telnet.patch
- patches/707-enable-board-name.patch
- patches/708-define-aredn-network-ath79.patch
- patches/708-define-aredn-networks.patch
- patches/710-no-ping6-traceroute6.patch
- patches/712-auto-distance-settings.patch
> aredn: update to openwrt v19.07.10 and patch refresh

- files/usr/local/bin/mgr/rssi_monitor.lua
And shut down if we hae no wifi to monitor
https://github.com/aredn/aredn/issues/226
> Improve rss_monitor startup

- files/www/cgi-bin/setup
This was accidentally setting it to ""
> Only preserve wan_intf if set

- files/usr/lib/lua/aredn/info.lua
I don't have a 3GHz radio to test this, so if someone could that'd be lovely, but it uses the same logic as getChannel()
https://github.com/aredn/aredn/issues/116
> Correct the frequency for 3GHz radio

- files/www/cgi-bin/advancedconfig
provide categories structure to advanced config page
> enhancement: advanced config categories

- files/www/cgi-bin/admin
Adapted from the original Perl sideload patch
https://github.com/aredn/aredn/issues/335
> Firmware sideload support

- files/usr/local/bin/node-setup
> Inverted test for different port forward

- files/usr/local/bin/mgr/lqm.lua
- files/www/cgi-bin/iperf
- files/www/cgi-bin/lqm
- files/www/cgi-bin/supporttool
Minor improvements:
Improve handling of disconnecting nodes, especially ones we're seeing for the first time.
Show 'disconnected' status
Remove extra body tag in iperf page
Add LQM info to support tool
> LQM fixes 3

- files/usr/local/bin/mgr/lqm.lua
Somehow this very important code got lost - sorry.
> Turn LQM off when not enabled!!

- files/www/cgi-bin/setup
- files/www/cgi-bin/vpn
- files/www/cgi-bin/vpnc
- files/www/help.html
- Add or verify help anchors, names, and hrefs to be working on all pages
- Add several entries and reformat Table of Contents
- Add Neighbor Status page description
- Add Audio Control info to Charts help
- Add Previous Neighbors to Mesh Status help
- Add Link Quality Manager description to help
- Add LAN Access Point and WAN Wifi Client to help
- Add DNS Aliases to ports help
- Add tunneling section to help
- Add Apply Local Firmware to admin help
> update the onboard node help file

- files/www/about.html
Correct registered service mark and copyright symbols, as well as consolidate display with minor format changes.
> correct registered service mark and copyright symbols

- files/www/cgi-bin/setup
Missing code to detect 5GHz devices for AP mode.
> Fix 5GHz AP bad channel dropdown

- files/www/cgi-bin/setup
Fix missing -4 and -3 channels
> Missing channels -4 and -3

- Makefile
- README.md
- config.mk
- feeds.conf
This reverts commit 265cb20096d23755365ae31b084c8abec7333750.
> Revert "aredn: Prepare the 3.22.6.0 release (#391)"

- files/www/cgi-bin/scan
3GHz is (naturally) odd, so this forces me to fix the limits of the graph based on the frequency band. On the plus side this simplified things.
> 3GHz fixes and optimizations

- files/www/cgi-bin/scan
Feedback from Joe and others to adjust the noise floor (which is lower
for subchannels). Label with SNR because that's easier to compare to the
SNR values people are already familiar with.
Add SNR to wifi scan table.
> Graph in SNR + fixes

- files/www/cgi-bin/setup
> allow zero length wan wifi client passphrase

- files/www/cgi-bin/scan
Some local analysis of the spectral data to reduce what needs to be sent over the wire (so page loads much quicker) which also allows a "heap map" showing how many transmissions occur at what power and at what frequencies.
> Heat map spectral view

- files/www/cgi-bin/setup
> Fix tacticalname

- files/www/cgi-bin/admin
Brings **Keep Settings** checkbox to the top showing that it applies to everything below. Also added category bars to the sections.
> make Keep Settings more prominent 07/19/2022

- files/www/cgi-bin/setup
https://github.com/aredn/aredn/issues/446
> wifi_chanbw should always be a string

- files/www/cgi-bin/setup
https://github.com/aredn/aredn/issues/447
> Fix issues with tactical names

- files/etc/init.d/local
https://github.com/aredn/aredn/issues/397
Credit to @pmilazzo for all the leg work on this.
> Deal with lan on AR300M always having the same mac address

- files/www/cgi-bin/advancedconfig
Group network-related settings in a **Network Tools** category.
> adjust admin categories

- files/www/help.html
Add the new Advertised Services check explanation to the help.html file.
> update html help file for adv svc feature

- files/www/cgi-bin/setup
- files/www/cgi-bin/status
> Prefix 'WiFi' to WAN address when WiFi wan is enabled

- files/www/cgi-bin/scan
There was some discussion about a point release tonight, especially in light of the recent security fix. We decided to pull this feature (but keep the kernel api in place) for now.
> Remove spectral scan for further development

- files/www/help.html
Update the on-node help file for the change in Advanced WAN Settings.
This PR goes with aredn #476
> update node help file for adv wan settings

- files/www/cgi-bin/setup
Fix for this issue - https://www.arednmesh.org/content/unable-save-change-nat-mode-32280
> Fix bad match for NAT dhcp address.

- files/usr/local/bin/mgr/lqm.lua
Nodes were occasionally including themselves as a neighbor. Let's not do that as it's confusing.
> Stop node's LQM neighbors including itself

- files/usr/local/bin/mgr/rssi_monitor.lua
Add an additional rescan trigger to the current system. Here if we detect the number of nodes going to zero (from non-zero), we trigger a scan. We only trigger the scan on this transition.
> Add a wifi scan trigger for when the nodes detected becomes zero

- files/usr/local/bin/olsrd-config
Add missing 3XX redirects (rare, but apparently in use)
Add 401 to allow services which require basic/digest authentication (some webcams need this)
> Add more 3XX redirects + 401 authentication

- files/etc/config.mesh/system
- files/etc/config/system
- files/usr/local/bin/recoverymode
remove bbhn prefix and fix bugs in recoverymode script
> fix recoverymode script

- files/etc/uci-defaults/82_aredn_ntp_period_migrate
- files/www/cgi-bin/setup
Allow users to set the NTP update period from a dropdown on the Basic Setup UI
> add ntp update period to basic setup page

- files/usr/lib/lua/aredn/utils.lua
- files/www/cgi-bin/admin
- files/www/cgi-bin/mesh
- files/www/cgi-bin/vpn
- files/www/cgi-bin/vpnc
Add warning/recommendation on 32mb node pages (admin, vpn, vpnc).
> add warnings to 32mb nodes

- files/www/help.html
Update the onboard node help.html file with clarification about the Host Entries on the Status page.
> clarify Host Entries counts

- files/www/cgi-bin/mesh
Add the ability to filter some of the key columns for _Current Neighbors_ and _Remote Nodes_ based on search characters entered in the column header fields.
> add search capability to Mesh Status page

- files/www/cgi-bin/mesh
Thanks for catching this, @aanon4 Tim.
> fix description alignment

- files/www/cgi-bin/mesh
Line up the columns on the mesh display.
> Line up the columns on the mesh display

- files/www/cgi-bin/mesh
Fix service search for Current Neighbor table and include search fields for all tables.
This PR also puts Previous Neighbors at the end of the Current Neighbors table.
> fix current neighbor service search and add new search fields 11/01/2022

- files/www/cgi-bin/advancedconfig
> give cleaner lines to adv config table 11/01/2022

- files/www/cgi-bin/scan
> give cleaner lines to the scan table 11/01/2022

- files/www/cgi-bin/mesh
Address the enhancement request in issue 530.
Fixes #530
> fix mesh search rows

- files/www/cgi-bin/status
If wifi_enabled then group all the relevant _Mesh RF_ information with the IP address.
**Status display with Mesh RF enabled and having RF links:**
**Status display with Mesh RF enabled but without RF links:**
**Status display with Mesh RF disabled:**
> group Mesh RF info if wifi_enabled

- files/www/cgi-bin/status
Reproduced Issue #558 and provided a fix for that issue as well as the unclosed _nobr_ tag. Fixes #558
> fix status page not rendering

- Makefile
- README.md
- config.mk
- feeds.conf
> Prepare the 3.22.12.0 release

- files/www/cgi-bin/mesh
Fix #571 -- alignment of local nodes mesh status display.
> fix local mesh status bug

- files/etc/local/mesh-firewall/05-xlink
> Fix xlink firewall rule

- feeds.conf
Make sure https://github.com/aredn/aredn_packages/pull/13 has also been committed.
> Fix aredn packages feed

- files/www/cgi-bin/status
This provides a way to aim nodes that are not yet linked using the audio tones.
> Display Charts button even when no RF links

- patches/800-upgrade-compatibility.patch
> Upgrade compatibility 3

- files/www/cgi-bin/admin
New opkg reports missing dependencies differently
> Fix package dependency auto update

- files/www/cgi-bin/setup
Improve meshrf conflict check which could be triggered even when no wifi is enabled
> Improve meshrf conflict check

- files/www/cgi-bin/iperf
> iperf - Add client/server at top of data for easier understanding

- SUPPORTED_DEVICES.md
proposed new format for discussion
> new SUPPORTED_DEVICES.md format

- patches/701-extended-spectrum.patch
Also update patch for -3 and -4 channels.
> Fix negative channels not beaconing.

- files/etc/local/mesh-firewall/01-tunnels
Data destined for the firewall endpoint was being blocked by bad rule ordering.
> Fix tunnel firewall

- files/usr/local/bin/mgr/lqm.lua
This was used during the transition to using LQM and is no longer needed.
> Remove LQM first run code

- files/www/cgi-bin/mesh
Fix Mesh Status page typos identified by Orv W6BI.
> fix mesh status typos

- files/usr/local/bin/mgr/lqm.lua
Rework the way RF links are blocked.
I've not been able to reproduce this (though its been reported by various people) so this is a more defensive approach to blocking in this case.
> Rework DTD blocking detection

- files/usr/local/bin/node-setup
Move the node-setup variable expansion into a function so we can reuse it.
> Generalize node-setup variable expansion

- SUPPORTED_DEVICES.md
> Update the status of some devices which have been tested

- SUPPORTED_DEVICES.md
> PowerBeam-M2-400 stable

- files/www/cgi-bin/iperf
A few improvements:
1. Stop iperf3 starting if it's already running which kills an active test. There's still a window for it to happen, but much improved.
2. Stop client starting if server fails to start.
3. Whitespace/formatting
> Iperf improvements

- files/etc/firewall.natmode
- files/etc/local/mesh-firewall/01-tunnels
- files/etc/local/mesh-firewall/05-xlink
- files/etc/local/mesh-firewall/10-lan-to-wan
- files/etc/local/mesh-firewall/21-lqm
- files/usr/local/bin/mgr/lqm.lua
I think I added these before I understood you didnt have to.
> Remove firewall counters except for specific ports

- files/etc/uci-defaults/45_aredn_reset_paths
- files/www/cgi-bin/advancedconfig
https://github.com/aredn/aredn/issues/637
> Make sure we look for packages with the correct architecture

- files/usr/local/bin/upgrade_prepare.sh
- files/usr/local/bin/uploadctlservices
- files/www/cgi-bin/admin
Improve the restarting of services if a firmware upgrade fails.
> Improve firmware failure error recovery

- patches/749-fix-tiny.patch
A bit of a guess as I dont have a device to test this on.
> Fix AirRouter

- SUPPORTED_DEVICES.md
Thanks for K1KY and @dman776 for checking these.
> A few more devices tested and stable

- RELEASE_NOTES.md
I'm proposing we keep a copy of the release notes in git for people who might want to easily refer to changes over many releases. I've copied the last 3 years of notes into the file. We'd update this file only when we make releases (not nightlies).
Thoughts?
> Propose adding copy of release notes to repo

- README.md
See https://github.com/aredn/aredn/issues/701
> Fix AirRouter port description

- files/usr/local/bin/mgr/lqm.lua
There is a problem in the arp cache where wifi ARP/IP pairs are assigned to the dtd device. Filtering these early doesnt work, so instead we filter these when rebuilding the dtdlink station list.
(Problems found while field testing some AC devices)
> Reworked ARP cache 02/11/2023

- files/www/cgi-bin/setup
Handle dual band non-hap radios where second band is 2GHz.
The whole radio selection/management needs to be revisited at some point later this year.
> Improve AP band selection.

- files/www/cgi-bin/setup
Fixes bad band label display on first boot
> Move the unconfigued setup earlier

- files/www/cgi-bin/mesh
In some cases the services were not correctly aligning with the dmz hosts.
> Fix service alignments

- files/usr/lib/lua/aredn/nettools.lua
- files/www/cgi-bin/iperf
Error reporting, especially when using the api interface, wasn't very helpful especially if iperf on the server was disabled.
> iperf: Improve error reporting when server is busy/disabled

- files/etc/local/mesh-firewall/03-dhcp-wan-block
https://github.com/aredn/aredn/issues/746
> Block DHCP server traffic from every going to the WAN interface 03/23/2023

- files/www/cgi-bin/ports
OLSR doesnt allow this and they wont be advertised.
> Dont let services uses hostnames which are not propagated.

- files/usr/local/bin/mgr/rssi_monitor_ath10k.lua
There appears to be a bug in the ath10k firmware for Mikrotik devices (maybe others) where a station will occasionally associate but only broadcast traffic will be passed - unicast traffic will fail. This code detects this situation and forces the device to reassociate which fixes the problem.
> Force badly associated stations to reassociate.

- SUPPORTED_DEVICES.md
I did the same thing I did to the mikrotik supported devices list to the gl-inet supported devices list
> update GL-inet supported devices list

- Makefile
- config.mk
- feeds.conf
> prepare 3.23.4.0

- files/etc/radios.json
https://github.com/aredn/aredn/issues/790
> Fix TP-Link CPE210 v3 capitalization

- .circleci/config.yml
last few nightly build pipeline only ran check, build, save steps.   This is an attempt to correct the flow.
> fix nightly pipeline only running check,build,save steps

- SUPPORTED_DEVICES.md
Just update SUPPORTED DEVICES to correctly note where this devices is supported.
> Note CPE210 V3 is nightly not release

- .circleci/config.yml
> fix circleci config.yaml

- patches/708-define-aredn-ath79-networks.patch
Tested on the ar750 and ar300m16 which both showed issues.
> Fix syntax error in patch that broke network on many ath79 devices

- files/www/cgi-bin/ports
Minor visual tidying of the ports screen to make things line up properly.
> Tidy up the formatting and fix column widths

- .circleci/config.yml
migrating our old circleCI workflow (trigger) to scheduled pipelines
> migrate circleci to pipelines and trigger schedule

- .circleci/config.yml
added "no_action" workflow and make it the default
> cci update default workflow

- files/www/cgi-bin/admin
This has come up a few times where people are unsure they've pressed the upload/download firmware buttons because the process can take a while. This just changes the text on the buttons when pressed.
> Feedback when pressing upload/download buttons

- .circleci/config.yml
ie. aredn-20230505-commit_id-xxxxx-yyy.bin
> cci improvements and change nightly build number to actual date

- SUPPORTED_DEVICES.md
- configs/ath79-mikrotik.config
- files/etc/radios.json
- patches/801-mikrotik-lhg-variants.patch
Thanks KM6SLF for loaning me the hardware.
> Mikrotik LDF2 support

- files/www/cgi-bin/setup
Fix for https://github.com/aredn/aredn/issues/851
> Fix disabled mesh on multi-wifi devices

- files/etc/config.mesh/firewall
- files/etc/local/mesh-firewall/12-wan-services
- files/www/cgi-bin/advancedconfig
Provide toggles to selectively re-enable web and ssh.
> Disable WAN access to node by default.

- files/etc/radios.json
- files/usr/lib/lua/aredn/controller/setup_basic.lua
- files/usr/lib/lua/aredn/hardware.lua
- files/usr/lib/lua/aredn/info.lua
- files/usr/local/bin/node-setup
- files/usr/local/bin/wscan
- files/www/cgi-bin/scan
- files/www/cgi-bin/setup
- files/www/cgi-bin/sysinfo.json
Add support for multi-radio power settings.
Update various radio api to take wifi as argument rather than assuming a specific interface.
> More multi-radio support

- files/usr/lib/lua/aredn/hardware.lua
https://github.com/aredn/aredn/issues/861
> Handle non-wifi devices passed to maxpower/pwroffset functions

- files/usr/lib/lua/aredn/nav/admin/65advancednetwork.lua
- files/www/cgi-bin/advancednetwork
x86 is a single port device, so the port section makes no sense for this device. But supporting xlinks is useful if you want to use x86 hardware (often quite a bit faster) for this feature.
> Support xlinks on x86

- files/www/cgi-bin/advancednetwork
Xlink endpoints can now be arbitrary IP addresses
> Remove subnet restrictions for xlinks

- files/usr/local/bin/mgr/wireless_monitor.lua
The arp cache keeps wifi entries long past them being associated with the node, so now use wifi assoc list to find nodes, and the arp cache to get their IPs.
> Use wifi assoc list when looking for unresponsive nodes.

- files/usr/lib/lua/aredn/info.lua
- files/usr/local/bin/wscan
- files/www/cgi-bin/admin
- files/www/cgi-bin/api
- files/www/cgi-bin/scan
* Fix the use of getFreq in various places.
* Dont compress the admin page so timeouts dont just show Bad Gateway errors
> RC: Day 1 fixes

- files/etc/radios.json
- files/usr/lib/lua/aredn/hardware.lua
Note. I also re-pretty-printed the JSON so it's more uniform.
> Lowercase the keys in radios.json

- files/www/cgi-bin/vpn
> fix error msg iss749

- SUPPORTED_DEVICES.md
Clarify when the "dangerous upgrade" package might need to be used.
> clarify install support status

- files/www/black_on_white.css
- files/www/cgi-bin/mesh
- files/www/cgi-bin/vpn
- files/www/cgi-bin/vpnc
- files/www/red_on_black.css
- files/www/white_on_black.css
- files/www/yellow_on_black.css
Unify the search fields into a single search at the top of the mesh page, rather than 9 search boxes for various fields. I think it's easier to find and use here.  Here's a visual. I also tweak the colors so it works when selecting different color styles.
> Simpler search

- patches/010-lz77-decompression-support.patch
- patches/series
See conversation in this issue https://github.com/aredn/aredn/issues/919
> Add LZ77 decompression for newer Mikrotik devices

- files/etc/mesh-release
- patches/series
This changed caused problems on older AC3 so revert it temporarily.
> Disable lz77 until problems resolved

- files/www/cgi-bin/setup
https://github.com/aredn/aredn/issues/921
> Correctly set wifi wan mode when depending on the mesh wifi setting

- files/usr/local/bin/mgr/lqm.lua
- files/www/cgi-bin/advancednetwork
Allow xlinks to broadcast OLSR traffic as well as targeting specific IPs.
> Xlink broadcast

- Makefile
- configs/common.config
Some developer need more than our stripped down cron system. Add a loadable cron daemon package they can use.
> Add installable cron package for people who need more functionality

- files/usr/local/bin/mgr/lqm.lua
Occasionally we excluded DtD neighbors (under very specific conditions). Attempt to fix this oversight.
> Lqm neighbor improvements

- files/usr/lib/lua/aredn/nav/user/23supermesh.lua
- files/usr/local/bin/olsrd-config
- files/www/cgi-bin/advancedconfig
- files/www/cgi-bin/mesh
* Fix supernode tunnel weight at 0
* Move Super Mesh button onto Mesh page
> Supernode improvements

- files/www/cgi-bin/sysinfo.json
> Implement nodes=1 in sysinfo.json to return number of mesh nodes

- files/www/cgi-bin/mesh
Rename Super Mesh to Cloud Mesh. I really dont like Super Mesh.
> Super Mesh -> Cloud Mesh

- files/usr/lib/lua/aredn/nav/admin/65advancednetwork.lua
- files/www/cgi-bin/advancednetwork
Improve vlan selection in advanced networking
Add the GLiNet B1300
> Improve vlan selection in advanced networking

- files/usr/local/bin/node-setup
> Fix wan client no encryption mode

- files/etc/radios.json
- files/usr/lib/lua/aredn/nav/admin/65advancednetwork.lua
- files/www/cgi-bin/admin
- files/www/cgi-bin/advancednetwork
Add VMware as a supported device type.
Works just like the other x86 device.
> VMWare support

- files/usr/local/bin/node-setup
- files/usr/local/bin/restart-services.sh
- files/www/cgi-bin/setup
Make sure switching wifi modes forces a reboot.
Because some hardware doesn't handle this well.
> Make sure switching wifi modes forces a reboot.

- files/www/cgi-bin/setup
- files/www/cgi-bin/status
Display all the antenna information on the front page
And provide more visible units.
> Display all the antenna information on the front page

- files/usr/local/bin/manager.lua
- files/usr/local/bin/mgr/hw_watchdog.lua
- files/usr/local/bin/mgr/olsrd_watchdog.lua
- files/usr/local/bin/node-setup
- files/www/cgi-bin/advancedconfig
The watchdog monitors three things:
1. A set of important system daemons.
2. A set of pingable ip addresses.
3. A time the node should reboot everyday.
> Watchdog support, initial version.

- files/etc/hotplug.d/iface/11-meshrouting
- files/usr/local/bin/node-setup
1. Allow wireguard tunnels in iface mesh setup (treat like vtuns)
2. Fix incorrectly setting up dtd/wifi to wan rules
> Fix firewall rules.

- files/usr/lib/lua/aredn/info.lua
- files/usr/local/bin/node-setup
Remove need to generate /etc/config/services file which was just there for one api call (data now generated another way).
> Remove need for /etc/config/services file

- files/www/cgi-bin/mesh
I can't be the only person who has to keep looking up what this means?
> Add some LQ and NLQ hint text.

- files/usr/local/bin/mgr/lqm.lua
- files/www/cgi-bin/vpn
Wireguard2 - bug fixes:
Fix _add
Fix LQM
> Wireguard2 - bug fixes

- files/usr/local/bin/mgr/lqm.lua
- files/usr/local/bin/node-setup
- files/www/cgi-bin/vpn
- files/www/cgi-bin/vpnc
Fix the server side wireguard address setup.
Fix the wireguard key field so you can copy the data and it being the data you want.
Fix the tunnel restarts when saving tunnels
Fix monitoring address bug
> More wireguard fixes

- files/www/cgi-bin/mesh
Add xlink display to remote nodes.
Fix LQ display of weighted local links.
Fix NLQ display of weighted links (using the LQ weight ... and assume its symmetrical)
> Improve mesh display

- files/www/cgi-bin/vpn
Wrap wireguard ip allocation, avoiding 254, 255, 0 and 1.
https://github.com/aredn/aredn/issues/1075
> Wrap wireguard ip addresses

- files/etc/radios.json
- files/usr/lib/lua/aredn/hardware.lua
- files/usr/local/bin/node-setup
- patches/011-fix-e750-reset-5g-crash.patch
- patches/series
https://github.com/aredn/aredn/issues/983
> Support for GL.iNet E750

- patches/749-ubiquiti-extra-support.patch
Fix the search name. Hopefully it's this easy.
https://github.com/aredn/aredn/issues/1025
> Fix PowerBeam 5AC 400 name

- files/www/cgi-bin/vpn
New supernodes which dont yet have any legacy tunnels are no longer permitted to create legacy tunnels. 
They may continue to have them if they already do, and they can join other supernodes servers with legacy tunnels, but they cannot create their own.  This is a step towards wireguard only supernodes.
> New supernodes no longer have access to legacy tunnels

- files/usr/lib/lua/aredn/nav/user/20lqm.lua
- files/www/cgi-bin/mesh
Merge available LQM information onto the mesh page so we finally have all this in one place.
> Merge the LQM info onto the Mesh page

- files/usr/local/bin/mgr/wireguard_watchdog.lua
This fixes up wireguard connections to dynamically changing IP addresses
> Run the wireguard watchdog script every 5 minutes

- files/www/cgi-bin/supporttool
> Hide wireguard keys in base config

- files/www/cgi-bin/mesh
Add <1 mile if distance to node is known but small.
Handle kilometers
> Mesh distance improvements

- files/www/cgi-bin/mesh
We were searching lots of empty fields, which just slowed things down for no reason.
> Improve speed of search

- files/www/lime_on_black.css
https://github.com/aredn/aredn/issues/1118
> Lime on Black style

- files/usr/lib/lua/aredn/olsr.lua
Identify xlinks in sysinfo.json reporting
> Improve xlink reporting in sysinfo

- files/usr/local/bin/mgr/lqm.lua
Investigating performance issues in nightly. Disable this feature.
> Disable reducing retry counts

- files/usr/local/bin/mgr/lqm.lua
Experimental wifi research reports that increased retries (rather than decreased as I originally thought) improves tcp throughput on multi-hop wifi networks.
> Increase wifi retries by default.

- files/www/cgi-bin/mesh
Fix neighbor display so it uses the new layout system.
> Fix display of previous neighbors

- files/usr/lib/lua/aredn/html.lua
https://github.com/aredn/aredn/issues/1131
> Fix missing cursor

- files/www/cgi-bin/iperf
Try to improve iperf reliability
> Rewrite iperf to make it more reliable

- files/etc/radios.json
- files/usr/lib/lua/aredn/hardware.lua
- files/www/cgi-bin/setup
- files/www/cgi-bin/status
- files/www/cgi-bin/sysinfo.json
https://github.com/aredn/aredn/issues/1100
> Add aux antenna support

- files/www/cgi-bin/vpn
- files/www/lime_on_black.css
https://github.com/aredn/aredn/issues/1107
> Fix black on black text on tunnel page

- files/www/cgi-bin/scan
If we disconnect then reconnect the radio then the wifi scan on the Ubiquiti AC will work for a short while.
> Ubiquiti AC wifi scan fix

- files/www/cgi-bin/scan
Use ?autoscan=1 to keep the page scanning rather than a file in the filesystem.
> Per page scan

- .circleci/config.yml
Update the release install path.
Add the afs step to release.
> Circleci release fixes

- files/etc/radios.json
Add definitions of the TX power and the pattern and gain of the internal antennae of the GL-B1300.
> Add antenna and TX-power definitions for GL-B1300.

- files/etc/antennas.json
- files/etc/radios.json
Add some missing antenna definitions for older Ubiquiti radios.
> Add some missing antenna definitions for older Ubiquiti radios.

- files/usr/local/bin/aredn_message.sh
Describe the goals that the pull request accomplishes.
If there are related issues, please link them here.
Please also include links relevant to the changes.
If applicable, please include screenshots before and after your changes.
Add any other context about the problem or changes here.
> fix extra curly brace

- .circleci/config.yml
Not sure of a better way to test this than just trying it - sorry for the noise.
> Experimental second downloads server

- files/usr/lib/lua/aredn/info.lua
- files/usr/local/bin/mgr/lqm.lua
- files/www/cgi-bin/status
- files/www/cgi-bin/sysinfo.json
Fix various problems when reporting channel and frequency information on 3GHz and 900MHz nodes.
Fix tunnel reporting
Stop LQM copying mac file when it hasn't changed.
> Fix various status information errors

- files/usr/local/bin/mgr/lqm.lua
- files/www/cgi-bin/mesh
Fix way packet transmissions errors are calculated.
> More LQM quality tracking improvements.

- files/usr/local/bin/mgr/lqm.lua
Remove nodes if they've had a quality of 0 for an hour.
They're gone, but the ARP cache tends to keep them around so we can't rely on that timing them out anymore.
> Remove nodes if they've had a quality of 0 for an hour.

- files/etc/antennas.json
https://github.com/aredn/aredn/issues/1199
> Mikrotik dish

- files/usr/local/bin/mgr/lqm.lua
Use system calls to get interface information rather than parsing information from "ifconfig".
Use "ip neigh" to get arp information, with better detection of devices which have gone away.
> Improve LQM interface detection

- files/etc/antennas.json
https://github.com/aredn/aredn/issues/1208
> More antennas

- files/usr/local/bin/mgr/lqm.lua
- files/www/cgi-bin/mesh
Improve leaf detection (renamed minroutes).
Need a leaf connection to have a major and minor end.
> Better leaf node detection

- files/usr/lib/lua/aredn/services.lua
Sometime the olsr services file get badly formatted entries - ignore them rather than fail.
> Ignore badly formatted services

- files/usr/local/bin/mgr/lqm.lua
- files/usr/local/bin/mgr/olsrd_watchdog.lua
1. Simplify the OLSR watchdog
2. Dont pull the routing table into LQM for supernodes. LQM tracks routes on nodes to help keep leaf nodes connected even when circumstances would probably prevent this. However on supernodes the routing table is massive and pulling this into LQM will frequently crash OLSRD. As we dont need this for supernode just dont do it for them.
> Olsrd crash fixes

- files/etc/uci-defaults/80_aredn_lqm
- files/usr/local/bin/mgr/lqm.lua
Fetch routes from kernel rather than OLSR
Fix xlink detection
> Fetch routes from kernel rather than OLSR

- files/usr/lib/lua/aredn/html.lua
widen alert message field on status page
> widen aam field on status page

- patches/749-ubiquiti-extra-support.patch
We already have a Rocket XW image
> Remove confusing Rocket addition to Bullet image

- files/www/cgi-bin/vpn
Fix wireguard network field label
> update wg tun sv NET label

- files/app/resource/css/user.css
https://github.com/aredn/aredn/issues/1271
> Enable copy-n-paste

- files/app/partial/tools.ut
- files/usr/share/ucode/aredn/messages.uc
https://github.com/aredn/aredn/issues/1276
> Disable wifi signal tool when not in mesh mode

- files/usr/local/bin/mgr/lqm.lua
https://github.com/aredn/aredn/issues/1287
> Handle old nodes with missing node details

- files/app/main/status/e/firmware.ut
https://github.com/aredn/aredn/issues/1294
> Fix the download + update button at the bottom of the dialog

- files/app/main/status/e/neighbor-device.ut
- files/app/partial/local-and-neighbor-devices.ut
https://github.com/aredn/aredn/issues/1293
> Handle out of range link quality multipliers

- files/app/main/status/e/neighbor-device.ut
- files/app/partial/local-and-neighbor-devices.ut
https://github.com/aredn/aredn/issues/1279
> Clickable local node info

- files/app/main/app.ut
https://github.com/aredn/aredn/issues/1271
> Cancel clicks if copy is active

- files/app/main/status/e/firmware.ut
https://github.com/aredn/aredn/issues/1296
> Compact firmware version info

- files/app/resource/css/admin.css
> Increase dialog height

- files/app/main/status/e/firmware.ut
Make sure button stays pinned to bottom.
> Keep update button at bottom of firmware dialog

- files/usr/local/bin/mgr/lqm.lua
On dtdlink, arping can fail (possibly because there are no routes to the device) when a normal ping would succeed. So fallback to a normal ping if arping fails.
> When arping fails, fallback on simple UDP ping

- files/app/main/status/e/tunnels.ut
https://github.com/aredn/aredn/issues/1306
> Fix tunnel notes

- files/app/resource/css/admin.css
- files/app/resource/css/user.css
https://github.com/aredn/aredn/issues/1314
> Make menu cursors consistent

- files/usr/local/bin/mgr/lqm.lua
Speed up initial LQM setup by delaying the sysinfo probe for 60 seconds after the node is first discovered.
This allows LQM to have some data earlier. Also randomize the refreshing of this data a little.
> Speedup initial LQM setup

- files/app/partial/radio-and-antenna.ut
- files/usr/share/ucode/aredn/hardware.uc
- files/usr/share/ucode/aredn/radios.uc
Add LAN and WAN wifi information to status page.
> Add more radio information to status

- files/app/main/status/e/network.ut
- files/usr/share/ucode/aredn/configuration.uc
Update the various DHCP values when we change the DHCP range.
I just completely forgot to do this originally :-(
NOTE: This does not update the aliases you may have created; but the old code didnt do that either.
> Fix changing DHCP range.

- files/app/main/status/e/network.ut
https://github.com/aredn/aredn/issues/1328
> Rewrite DHCP aliases when DHCP range changes

- files/app/main/firstuse.ut
- files/app/main/status/e/basics.ut
- files/app/main/status/e/radio-and-antenna.ut
- files/app/partial/password-ctrl.ut
- files/app/partial/password.ut
- files/app/partial/radio-and-antenna.ut
- files/app/resource/css/admin.css
Add password eyes to plaintext passwords.
https://github.com/aredn/aredn/issues/1331
> Add password reveal eyes in various places

- files/app/main/status/e/tunnels.ut
- files/app/resource/css/admin.css
But dont blur newly created tunnels.
> Blur wireguard keys.

- files/app/main/status/e/tunnels.ut
Forgot to save the tunnel name
> Fix missing legacy server tunnel name

- files/app/main/status/e/network.ut
https://github.com/aredn/aredn/issues/1345
> Set missing dhcp configuration option

- files/app/main/status/e/packages.ut
https://github.com/aredn/aredn/issues/1349
> Add version number to packages in remove dropdown

- files/app/main/status/e/basics.ut
- files/app/main/status/e/firmware.ut
- files/app/resource/css/admin.css
- files/app/resource/css/themes/dark.css
- files/app/resource/css/themes/high-contrast.css
- files/app/resource/css/user.css
Experimental high contrast, larger typeface theme.
Feedback on this appreciated.
> Add high contrast / larger typeface theme.

- files/www/cgi-bin/status
Force navigations to the node's / to go to the new UI.
> Force the new UI to be the default

- files/app/main/status/e/neighbor-device.ut
- files/usr/local/bin/mgr/lqm.lua
> More neighbor stats

- files/app/partial/radio-and-antenna.ut
- files/usr/local/bin/node-setup
> Add Wifi Client status info

- files/app/main/status/e/firmware.ut
- files/app/resource/css/admin.css
Fix double scrollbar on some platforms
https://github.com/aredn/aredn/issues/1364
Better scrollbar spacing
https://github.com/aredn/aredn/issues/1363
> Improve firmware layout

- patches/749-ubiquiti-firmware-version.patch
https://github.com/aredn/aredn/issues/1360
> Support newer powerbeam acs

- files/app/resource/css/themes/high-contrast.css
Drop base font size from 19px to 18px.
> More high contast changes

- files/app/main/firstuse.ut
- files/app/main/status/e/internal-services.ut
- files/app/main/status/e/network.ut
- files/app/main/status/e/radio-and-antenna.ut
- files/app/partial/hideable-onselect.ut
- files/app/partial/hideable-switch.ut
- files/app/partial/mesh.ut
- files/app/partial/password-ctrl.ut
- files/app/partial/password.ut
- files/app/resource/css/admin.css
- files/app/resource/css/user.css
> Remove functional use of :has css so we can support older browsers.

- files/usr/share/ucode/aredn/configuration.uc
* Handle values with = in them.
* Convert newlines to spaces.
> Improve settings parsing.

- files/app/partial/nav.ut
?. syntax not available in older browsers.
> Remove syntax not supported in older Javascript

- files/app/main/status/e/dhcp.ut
- files/app/main/status/e/local-services.ut
- files/app/main/status/e/ports-and-xlinks.ut
- files/app/main/status/e/tunnels.ut
https://github.com/aredn/aredn/issues/1409
> Use ENTER to add more new entries in various places

- files/app/main/tools/e/iperf3.ut
- files/app/main/tools/e/ping.ut
- files/app/main/tools/e/traceroute.ut
Apparently there's a HTML construct called datalists which are used with text input to provide autosuggestions. Since 2011. Who knew.
> Use autocomplete inputs to select nodes in tools

- files/app/main/app.ut
- files/app/main/status/e/basics.ut
- files/app/partial/mesh.ut
- files/app/root.ut
- files/etc/uci-defaults/99_canonical_config
Features:
* Portable theme - bring your localnode theme with you on the mesh.
Bugs:
* Versioned resources were not being typed, causing Firefox to error and load the slow version from across the mesh. This defeated the localnode resource caching benefits.
* Fix names of versioned resources. Format was X.TYPE.VERSION and is now X.VERSION.TYPE which is more sane and easier to manage in the server.
> Fix themes and resource caching

- files/app/main/status/e/tunnels.ut
- files/www/cgi-bin/vpn
Because we can delete tunnels in the new UI, this will cause problems in the old UI which doesnt support this. Warn when we detect this.
> Detect new UI in old server tunnels so we can warn

- files/app/main/status/e/tunnels.ut
https://github.com/aredn/aredn/issues/1445
> Fix supernode start port

- .circleci/config.yml
Bump our build to the next class (large -> xlarge) to see if it improves build times.
Set make parallelism to nr_cpus + 1 (9 in this case) as recommended in OpenWRT docs.
> Bump up to xlarge resource class

- files/app/main/status/e/local-services.ut
WAN capitalized; should have been wan
> Fix WAN port forwarding.

- files/app/main/status/e/radio-and-antenna.ut
- files/www/cgi-bin/sysinfo.json
Fix misnamed LQM toggle.
Report LQM information even when LQM is disabled (it has data which is still useful).
> Fix LQM reporting and toggle

- files/etc/local/mesh-firewall/04-wireguard
The old UI let you turn this off. We dont let you do that anymore.
> Make sure wireguard firewall is always on

- files/usr/local/bin/mgr/lqm.lua
When links are idle, we can't ping them directly and indirectly pinging them (the ping is routed) doesnt measure what we want. So we just dont ping them and let any old ping failures decay.
> Dont ping unroutable links

- files/app/partial/mesh-data.ut
When a node is installed and doesnt have any friends yet, the mesh page was broken and empty. Fixed.
> Better mesh empty page

- files/app/main/app.ut
- files/app/main/firstuse-ram.ut
- files/app/main/firstuse.ut
Add missing charset so we handle utf8 encoding correctly.
> Add missing <meta charset="utf-8">

- files/app/main/status/e/tunnels.ut
Once you have tunnels, changing the tunnel start value would cause problems.
> Prevent tunnel start address change if there are any server tunnels

- files/app/main/status/e/firmware.ut
Improve handling is malformed metadata and partially downloaded files.
> Improve error reporting when firmware downloads fail

- files/app/main/status/e/tunnels.ut
> Recalculate tunnels address range when tunnel server network changes

- files/app/partial/local-and-neighbor-devices.ut
Describe blocked state in more detail
> Improve link status hint text

- files/app/main/status/e/network.ut
- files/usr/local/bin/node-setup
Remove the switch and fold into the WAN mode selector (like the LAN size above it)
> Improve and simplify WAN config

- files/app/main/firstuse.ut
- files/app/partial/reboot-firmware.ut
1. Make sure mac2 is defined before setting up node (can take a while)
2. Avoid cross-origin problem when resetting node configuration
> Improve install process.

- files/app/main/app.ut
- files/app/main/status/e/dhcp.ut
- files/app/main/status/e/local-services.ut
- files/app/main/status/e/ports-and-xlinks.ut
- files/app/main/status/e/tunnels.ut
Provide a generalize form based mechanism to validate dialog content, and enable/disable the Done button as appropriate.
> Disable Done button when invalid dialog content

- files/app/partial/health.ut
> More visual tweaks

- files/app/partial/health.ut
- files/app/partial/radio-and-antenna.ut
> More UI tweaks

- files/app/resource/css/admin.css
* Stop the dialogs being squashed
> More minor visual tweaks

- files/app/main/status/e/internal-services.ut
- files/usr/local/bin/mgr/hw_watchdog.lua
https://github.com/aredn/aredn/issues/1311
> Watchdog improvements

- files/app/main/tools/e/iperf3.ut
- files/app/main/tools/e/ping.ut
- files/app/main/tools/e/traceroute.ut
https://github.com/aredn/aredn/issues/1609
> Add date and time to ends of various tool traces

- files/app/main/status/e/local-services.ut
- files/app/resource/css/admin.css
- files/app/resource/css/mobile.css
> Mobile layout work (2)

- files/app/main/status/e/neighbor-device.ut
- files/app/main/status/e/ports-and-xlinks.ut
- files/app/main/status/e/tunnels.ut
- files/app/resource/css/admin.css
- files/app/resource/css/mobile.css
* Xlinks, ports and devices
* Tunnels
> Mobile layout work (3)

- files/app/main/authenticate.ut
- files/app/partial/login.ut
- files/app/root.ut
/a/authenticate allowed POST access when not authenticated unlike every other path. Change authentication to use GET to avoid this anomaly.
> Remove special casing for /a/authenticate page

- files/app/main/app.ut
- files/app/main/status/e/firmware.ut
- files/app/main/status/e/location.ut
- files/app/main/status/e/packages.ut
- files/app/resource/css/admin.css
- files/app/resource/css/mobile.css
* Commit/Revert changes
* Field widths
* Logo link
> Mobile layout work (4)

- files/app/main/status/e/firmware.ut
- files/app/resource/css/mobile.css
* Reboot screen
* Firmware update screen
> Mobile layout work (5)

- files/etc/radios.json
- files/usr/share/ucode/aredn/hardware.uc
Add support for 40 and 80 MHz channels on AC radios which support this (they all do I think).
> Support wider channels (experimental)

- files/app/main/status/e/internal-services.ut
- files/app/partial/internal-services.ut
- files/etc/config.mesh/aredn
- files/etc/uci-defaults/99_canonical_config
- files/usr/local/bin/mgr/wireless_monitor.lua
There is a wifi watchdog service which runs in the background. This provides some UI to modify its behavior.
> Provide UI for the wifi watchdog system.

- files/usr/local/bin/mesh-firewall
- files/usr/local/bin/node-setup
> Remove setting old dmz value

- files/app/main/app.ut
- files/app/main/tools/e/iperf3.ut
- files/app/main/tools/e/ping.ut
- files/app/main/tools/e/traceroute.ut
- files/app/partial/tools.ut
- files/app/resource/css/mobile.css
Add the console based mobile tools.
> Add some mobile tools

- files/app/main/tools/e/wifisignal.ut
https://github.com/aredn/aredn/issues/1313
> Improve help for mobile wifi signal tool.

- files/app/main/status/e/tunnels.ut
https://github.com/aredn/aredn/issues/1707
> A few minor tunnel fixes

- files/app/main/inject.ut
- files/app/main/neighbor-device.ut
- files/app/partial/activator.ut
- files/app/partial/status.ut
- files/app/resource/css/user.css
Refine the htmx activation mechanism used to import JS and CSS on demand. Previously the mechanism had activated the entire UI which wasn't the goal.
> Refine htmx activation mechanism

- files/usr/local/bin/backup
- files/usr/share/ucode/aredn/configuration.uc
https://github.com/aredn/aredn/issues/1728
> Command line backup util

- files/app/main/status/e/dhcp.ut
- files/usr/local/bin/node-setup
Although it looks like OpenWRT document this, they dont implement it yet.
> Add rapid-commit (dhcp) option.

- files/app/main/status/e/dhcp.ut
- files/usr/local/bin/node-setup
(also minor fixups on some patterns)
> Support DHCP Options without values

- files/app/resource/css/admin.css
Some people see this, but I cannot reproduce it, which makes fixing it tricky. So ... a guess.
> Attempt to stop the dhcp reservation wrapping.

- files/app/main/tools/e/syslog.ut
- files/app/partial/tools.ut
- files/app/resource/css/admin.css
- files/app/resource/css/user.css
A basic syslog tool for easy access to a node's logging.
There is only one log file now, so we dont need to access different ones.
No highlighting for now - what do people want to see? Are there good examples of this I can look at?
> Basic syslog tool

- files/www/cgi-bin/ping
- files/www/cgi-bin/traceroute
This is more reliable than letting the tools guess.
> Fix the source addresses for pings and traces

- files/app/resource/css/mobile.css
> Make sure we hide any overflowed nav controls

- files/app/resource/js/meshpage.js
Changes to how mesh pages refresh forgot to reset the categories.
> Fix meshpage refresh

- files/app/main/status/e/dhcp.ut
- files/app/main/status/e/network.ut
- files/app/partial/dhcp.ut
- files/app/partial/dialog-footer.ut
Separate the LAN DHCP server enable/disable from the network setup options, and move the switch to the LAN DHCP panel. You can have the LAN configured but the server disabled, which wasn't well represented in the UI before.
> Move the LAN DHCP enable/disable option into the LAN DHCP panel

- files/app/partial/mesh-summary.ut
- files/usr/share/ucode/aredn/mesh.uc
More accurately count devices on the mesh.
Count services and display.
> Improve mesh device and service counts

- files/usr/local/bin/mgr/lqm.lua
The arp/neighbors ends up with bad entries sometimes which confuses LQM when tracking routes. This is a display problem rather than functional. Still, better to have it look correct.
> Fix display problem when arp contains bad entries

- files/app/main/status/e/radio-and-antenna.ut
More than that makes little sense other than to convey a false sense of accuracy.
> Provide 1 decimal point of significance to maximum distance.

- files/app/main/status/e/radio-and-antenna.ut
- files/usr/share/ucode/aredn/radios.uc
Switching modes is tricker now (more modes) so reworked this to make it more consistent.
> Rework default setup of radios when switching modes.

- files/app/main/status/e/radio-and-antenna.ut
- files/app/resource/css/admin.css
Do a better job at working out the default for the different radio modes to avoid round-tripping the setup data when the mode changes. Much better experience on slow networks.
> Improved radio setup

- files/usr/local/bin/mgr/lqm.lua
- files/usr/local/bin/node-setup
Make sure wpad is running in station mode (not just ap mode)
Improve poor json parsing.
> PtxP fixes

- files/app/main/status/e/radio-and-antenna.ut
- files/usr/share/ucode/aredn/radios.uc
The wifi standard imposes restrictions on which channel is used as the center channel for various wide bandwidth configurations. Honor these in the UI.
> First cut at wide channel restrictions imposed by the radios

- files/app/main/status/e/firmware.ut
This can cause firmware downloading to timeout sometimes.
> Fix firmware download progress parsing

- files/app/main/status/e/radio-and-antenna.ut
- files/usr/share/ucode/aredn/radios.uc
hostapd currently blocks the use of certain channels. Until we can resolve that, dont let the UI pick them.
> Block the use of certain channels in PtxP modes (for now)

- files/usr/lib/lua/aredn/services.lua
- files/usr/local/bin/node-setup
https://github.com/aredn/aredn/issues/1929
> Do a better job advertising hostnames in NAT mode

- files/usr/lib/lua/aredn/info.lua
sysinfo.json was reporting PtxP radio modes as "off".
> Detect new radio modes

- files/usr/share/ucode/aredn/babel.uc
It looks like the ucode rtnl library has a memory leak, so switch to parsing the output of ip-routes instead.
> Avoid possibly memory leak in retrieving babel host routes

- .circleci/config.yml
- Makefile
- SUPPORTED_DEVICES.md
- configs/mediatek-filogic.config
- files/app/main/status/e/firmware.ut
- files/etc/radios.json
- files/usr/share/ucode/aredn/hardware.uc
- patches/754-openwrt-one.patch
- patches/series
Thanks go to the Software Freedom Conservancy for the devices to make this happen.
> Add initial support for OpenWRT One

- files/usr/local/bin/mgr/lqm.lua
With Babel we treat the endpoint addresses for tunnels and xlinks as link-local addresses. This means they are no longer distributed as part of the mesh routing table because they only matter to the nodes at each end of the link. This causes some trouble for LQM when it comes to monitoring these links as it no longer has a route to the other end for the endpoint IP. Fortunately we can use IPv6 to solve this problem, as it has default support for IPv6 link local addresses, and it's what Babel already uses. We should utilamately move to entirely IPv6 link local monitoring once OLSR is gone, but that will take a while and this will, unfortunately, continue to be messy until then.
> Handle missing IPs from tunnels and xlinks.

- files/etc/dnsmasq.conf
- patches/703-disable-ipv6-dnsmasq.patch
- patches/series
Plus remove redundant domain= (defined in the generated config)
> Filter out AAAA dns responses

- files/app/main/firstuse-ram.ut
- files/app/main/status/e/firmware.ut
- files/usr/local/bin/aredn_sysupgrade
aredn_sysupgrade now has better firmware testing.
Add --force and --firstuse options.
Fix broken Mikrotik from RAM install (needed the options above)
> Improve sysupgrade process.

- files/usr/local/bin/mgr/lqm.lua
- files/usr/share/ucode/aredn/hardware.uc
Problem was seen when running x86 on Vultr.
> Vultr: Make sure we handle unsupported x86 platforms gracefully.

- files/usr/local/bin/mgr/lqm.lua
Getting a bit specific, and a bit messy, trying to handle old nodes and future nodes.
This is a lot cleaner once OLSR is gone ... thankfully.
> Handle detection of non-routing babel-only dtdlink neighbors.

- files/app/main/status/e/radio-and-antenna.ut
- files/app/partial/radio-and-antenna.ut
- files/usr/local/bin/mgr/lqm.uc
- files/usr/share/ucode/aredn/hardware.uc
HalowLink device has default ack timeout set 300us. Let the system optimize that and support greater.
> Support long distance HaLow links.

- files/usr/local/bin/node-setup
> Fix bad rule in firewall (babel only)

- files/usr/local/bin/node-setup
https://github.com/aredn/aredn/issues/2133
> Fix service addresses

- SUPPORTED_DEVICES.md
- files/etc/radios.json
Currently support is buggy, so disable for now.
> Disable the 2.4GHz radio in halow devices.

- files/etc/radios.json
But do it the right way this time.
> Disable secondary radio.

- files/etc/hotplug.d/iface/11-meshrouting
- files/usr/local/bin/node-setup
This had got messy, difficult to understand, and in some cases just broken.
> Completely rewrite the routing rules.

- files/etc/arednsysupgrade.conf
- files/usr/share/ucode/aredn/configuration.uc
Removing files that the babel build doesnt have.
> More backup and support data improvements.

- files/etc/hotplug.d/iface/11-meshrouting
Which is a pity because I'd rather not provide that level of access by default. There might be a better way to do this but will leave that for another day.
> Must allow LAN subnet access to WAN subnet for port forwarding to function

- files/app/main/status/e/firmware.ut
On the plus side, the actual saving and restoring of the data happens. Pretty much everything else about the process was broken though.
> Fix broken reboot when restoring.

- files/app/main/status/e/firmware.ut
Patch from babel-only version.
> Autoselect correct upgrade firmware after refresh.

- files/etc/arednsysupgrade.conf
- files/usr/local/bin/aredn_sysupgrade
> Revert "Dont preserve babel state across upgrades"

- files/app/partial/local-and-neighbor-devices.ut
But at the cost of showing some nodes as just IP addresses for longer.
> Speed up status page by avoiding dns lookups.

- files/app/main/app.ut
- files/app/partial/cloud.ut
- files/app/partial/map.ut
- files/app/partial/mesh.ut
- files/app/partial/nav.ut
- files/app/partial/selection.ut
- files/app/resource/css/user.css
- files/app/root.ut
When operating as an install webapp, open the cloud and map pages in the app rather than the browser.
> Add cloud and map pages to webapp

- files/usr/local/bin/mgr/babel_monitor.lua
See https://github.com/aredn/aredn/pull/2396 for more details
> Monitor Babel and restart if necessary.

- files/usr/local/bin/mgr/wireless_monitor.uc
When we detect unresponsive nodes we now restart with wifi mode but in NOHT mode, which is about as basic as you can get. Better to have a working link than one which keep flaking out.
> Aggressively turn down wifi high-throughput support on error.

- files/app/main/status/e/tunnels.ut
> Fix allow range of tunnel costs
