- How to Use GitHub for AREDN.md
Caught a couple of references to "master" and changed to correct repo name.
> Update branch and repo names in HowTo

- Makefile
temporary fix until received from upstream
The feed is being removed because:
a) it is an external project and the OpenWrt team does not have access to it.
b) upon original addition of the feed, there was only a very weak tendency for the addition.
c) there is a general lack of interest in the freifunk repo to review and/or merge pull requests.
d) as far as can be found, all projects which use the freifunk feed have their own make system and self-maintained feeds list. They do not use the feeds.conf.default from the openwrt repo.
more information can be read at the following links:
http://lists.openwrt.org/pipermail/openwrt-devel/2021-February/033807.html
freifunk/openwrt-packages#37
> bugfix: remove freifunk feeds

- files/www/cgi-bin/perlfunc.pm
Update the alert banner background color to distinguish it from the 
"supported hardware" messages. This makes it look more like a standard 
sticky note.
> Update alert banner background color

- files/www/cgi-bin/ucifunc.pm
uci_set_indexed_option() inserted an empty section on every call
because uci_get_sectiontype_count() always returned 0
> bugfix: uci_set_indexed_option() inserting multiple empty sections

- files/etc/init.d/vtund
Trivial fix, same as the one to vtundsrv in f4a1e73189862f6308de54deffa2862b2fafb17c
> bugfix: Tunnel servers limited to 9 - same fix as vtundsrv in f4a1e73

- files/www/cgi-bin/api
Fix spike to zero in SNR Chart.
Chart before fix:
Chart after fix:
> bug: Fix spike to zero in SNR Chart

- files/usr/lib/lua/aredn/info.lua
Format uptime as a string with values for days, hours, minutes, and seconds.
Added this to /usr/lib/lua/aredn/info.lua in the model.getUptime function.
> Format Uptime as String

- files/usr/lib/lua/aredn/olsr.lua
In olsr.lua there are gsubs to remove dtdlink and mid prefixes.  Add a gsub to remove the local.mesh suffix from hostname too.
> Remove local.mesh suffix from CurrentNeighbor hostname

- files/usr/lib/lua/aredn/info.lua
Remove the local.mesh suffix from hostnames returned through the **api** for the newui Local Hosts display.
> Remove local.mesh suffix from Local Hosts hostname in newui

- files/usr/lib/lua/aredn/olsr.lua
Fix regex for mid%d.hostname. It's possible that there may be more than a single digit. This PR also puts all the string.gsub processing in the if-else for _host_ rather than _remhost_.
> Fix regex for current neighbor midxx.hostname

- files/usr/lib/lua/aredn/info.lua
- files/usr/lib/lua/aredn/olsr.lua
- files/www/cgi-bin/api
Add the RF IP address for non-RF linked devices. This allows the services to be displayed for non-RF Current Neighbors.
> api: add RF IP for non-RF links

- files/www/cgi-bin/api
~~Displays~~ Returns the network topology in a nice json format.
Shows much more information than the "dotdraw" plugin and is in a different format than the "dotdraw" plugin.
> aredn: added network topology to mesh info API

- files/usr/local/bin/snrlog
Add default values to snr variables to avoid fatal errors that prevent snr.dat and snrlog/files from being written.
This workaround fixes issue #130
> aredn: fix snrlogging issue

- files/www/cgi-bin/api
Include the api_version in the info table so it can be displayed in System card on newui.
> api: show version in info table

- openwrt.mk
Security fixes
Fix FragAttacks (fragmentation and aggregation attacks) vulnerabilities in cfg80211, mac80211, ath10k and ath10k-ct
We are not sure if some closed source firmware files are still affected by these problems.
Security Advisory 2021-08-01-1 - XSS via missing input validation of host names displayed (CVE-2021-32019)
Security Advisory 2021-08-01-2 - Stored XSS in hostname UCI variable (CVE-2021-33425)
Security Advisory 2021-08-01-3 - luci-app-ddns: Multiple authenticated RCEs (CVE-2021-28961)
Various security fixes in packages
> openwrt: bump version to 19.07.08 to address security fixes

- feeds.conf
Switch to using develop branch of aredn_packages so we can include new fixes.
> Use develop branch for packages

- files/etc/config.mesh/aredn
- files/www/cgi-bin/advancedconfig
- files/www/cgi-bin/mesh
Based on feedback from the Meshoween event, this diff does a few things:
1. Remove a nested loop which was filtering out neighbor nodes in the "Remote Nodes" section. This scaled O(N^2) as the number of mesh nodes increased and was probably the big reason mesh status ground to a halt on resource constrained nodes.
2. Reduce the size of various in-memory hash tables built when generating the page and discarding them sooner.
3. Detect low memory nodes and limit the size of the mesh status page generated to only closer nodes.
4. For the Remote Nodes section, print as we go. This can get big so let's not keep it in memory.
5. When reading link speeds, reduce reads of the arp tables and wifi files as these are slow.
6. A bunch of little things for small speedups and memory savings.
Note: I …
> Meshoween: Mesh status page optimizations

- CONTRIBUTORS
- files/www/cgi-bin/admin
Fixes ath79 validation issue reported at https://www.arednmesh.org/content/upgrade-issue-ath79-nightly-filename
The regex now matches either underscore or hyphen character between hwmanuf and model, tested locally with different filenames and appears to solve the issue as reported.
(Deliberately modifying as little of the logic here as possible as I'm not the original author.)
> admin page: Fix validateFirmwareFilename() for underscore in ath79 filenames

- files/usr/local/bin/olsrd-config
This is a fix for a long running problem where, very occasionally, nodes don't publish their name until OLSRD is restarted.
The situation happens when OLSRD starts before the Wifi interface is completely up. At startup the name service plugin in OLSRD checks the list of names and services it has configured and removes any which don't have a corresponding, valid, interface. Unfortunately, if an interface becomes valid later, these entries are not added back in. They're gone until OLSRD restarts.
This fix waits until the wifi interface is available and up before allowing OLSRD to startup.
The code is not ideally placed, but I think better here than changing the OLSRD name service to fix the issue, or modifying core packages. I'm open to other options for where this could go.
Should fix: …
> Make sure wifi is up before letting OLSRD run

- files/etc/init.d/local
A 'config alerts' section was being added to the config on every reboot because this check will always be true if an alerts URI hasn't been set. Now it will only get added if it doesn't exist which seems more correct.
> Stop creating 'config alerts' on every reboot.

- .circleci/config.yml
increase no-output timeout from 10m to 30m
> build: increase build no-output timeout limits

- config.mk
- files/etc/uci-defaults/45_aredn_reset_paths
- files/www/cgi-bin/perlfunc.pm
standardize the nightly build/snapshots directory paths to remove the 'trunk' from /snapshots/trunk/
in support of the AREDN Firmware Selector tool
Also need to modify the CircleCI environment variable NIGHTLY_DIR before merging
> remove 'trunk' from snapshots path

- .circleci/config.yml
adding a build pipeline step to collect all firmware files for AREDN Firmware Selector tool (AFS)
> build: add AFS collector step to pipeline

- files/usr/lib/lua/aredn/hardware.lua
- files/usr/local/bin/mgr/linkled.lua
* Flash the LED slowly when no link found.
* Handle the LED exceptions where there is no 'correct' definition in board.json
We should fix the board.json creation process to add the correct link led definition, but for now just reflect the
exceptions currently in the Perl code. In fact, these aren't necessarily correct (the one I checked wasn't) so it
probably requires someone with access to devices actually making sure we do the right thing.
Spreadsheet of leds according to the current build code: https://docs.google.com/spreadsheets/d/1-kUm4GpUwlrVnHdr4xzSoVxGtPmMZS8x/edit?usp=sharing&ouid=104861343244109655077&rtpof=true&sd=true
* See https://github.com/aredn/aredn/issues/203
* Also https://github.com/aredn/aredn/issues/211
> Link led fixes

- files/www/cgi-bin/mesh
Node count is off by one on the mesh page. This is the same fix that was added to the status page.
> Fix node count (similar fix to status page) on mesh page

- files/usr/local/bin/bbhn-postupgrade
- files/usr/local/bin/node-setup
- files/usr/local/bin/node-setup.pl
- files/www/cgi-bin/perlfunc.pm
- files/www/cgi-bin/ports
- files/www/cgi-bin/setup
- files/www/cgi-bin/setup.pl
The setup page is the first major "writable" page to test (and associated node-setup backend). It has a lot of configurations depending on the device so testing on various different devices and configuration is desirable. Because this page can modify the configuration state it could very easily **brick your node** and require physical access to fix ... but hopefully not.
The old setup page his renamed "setup.pl"
> Lua userpages: setup

- files/usr/local/bin/mgr/rssi_monitor.lua
This avoids some startup failures where we try to detect the antenna setup
too early in the node boot up process.
> Move multi ant detection into main run method

- files/usr/local/bin/node-setup
Lua is stricter about comparing the equality of strings and numbers than Perl.
These fixes better handle the dmz_modes given this.
https://github.com/aredn/aredn/issues/233
> Fix dmz_mode handling

- files/usr/lib/lua/aredn/olsr.lua
If we fail to retrieve information from OLSRD, make sure we don't fail, instead returning empty arrays (which seems like an appropriate default).
https://github.com/aredn/aredn/issues/231
> Protect against OLSRD returning nil results

- files/usr/local/bin/node-setup
Rather important commas missing in DHCP options
> Missing commas in dhcp options

- files/www/cgi-bin/setup
One path through the reboot process requires a cursor we didn't have.
Also, incorrect name for IP address.
https://github.com/aredn/aredn/issues/231
https://github.com/aredn/aredn/issues/223
> Missing cursor during reboot

- files/www/cgi-bin/setup
When a node is first flashed and setup is called, things are a little different which caused various setup issues (resulting in the dreaded "Bad Gateway" error). Fixed.
> Fixes for first boot setup

- files/usr/local/bin/node-setup
== 1 isn't the same as == "1" in Lua
https://github.com/aredn/aredn/issues/249
> Fix txpower enable comparison

- files/www/cgi-bin/setup
During initial node setup, the node should auto reboot on the first-save, but this was broken.
> Fix broken auto-reboot on initial setup

- files/usr/local/bin/node-setup
Patterns were a little too loose and could match poor content causing failures
> Fix poor dhcp and alias patterns.

- files/www/cgi-bin/setup
Remove the potentially problematic 'filecopy("/etc/config/aredn", "/etc/config.mesh/aredn")'
/etc/config.mesh/aredn sometimes gets truncated, although reproducing it is difficult. This
is one of the few (only?) places this file is mindlessly written to, so instead use cursors to update it.
https://github.com/aredn/aredn/issues/253
> Remove potentially problematic copying of /etc/config.mesh/aredn

- files/www/cgi-bin/advancedconfig
Was using 'uci:cursor' and not 'uci.cursor' which appears to work but
actually breaks config files causing them to be truncated.
https://github.com/aredn/aredn/issues/253
> Fix broken cursor use.

- files/www/cgi-bin/scan
The Lua version was trying to remove duplicates based on mac addresses, but this didn't match what the Perl version was doing. Now it does.
> Make wifi scanning produce the same results as the perl version.

- files/usr/lib/lua/aredn/hardware.lua
- files/usr/lib/lua/aredn/utils.lua
- files/usr/local/bin/node-setup
Well ... Joe @ae6xe  did warn me this was more complicated than I through ... so here we are.
Some nodes assign multiple ethernet devices to each "virtual" device (e.g. lan, wan, etc.) are much of this code didn't understand this. A earlier fix solved some of these issue, but didn't add all the ethernet to bridges correctly.
Also broken was the creation of the dtdlink which can also be a bridge, even if only one device is attached to it.
I suspect more subtleties will be discovered here, but for now this solves known problems with older NSM2/5 devices.
> Network fixes for older nodes using bridges

- files/usr/local/bin/node-setup
Service names, which were not links, were being saved with a missing port number - breaks advertising them
> Fix url format for no-link service names

- files/www/cgi-bin/mesh
If link quality information is bad, mesh page was failing (bad gateway). Ignore bad information instead.
> Mesh ignore bad linkquality

- files/www/cgi-bin/vpn
- files/www/cgi-bin/vpnc
Create /etc/config/vtun if it doesn't exist, but don't truncate it if it does.
> Dont truncate /etc/config/vtun on tunnel install

- files/www/cgi-bin/vpn
https://github.com/aredn/aredn/issues/276
> Tunnel's default IP is explicitly based on eth0's MAC (not 'lan')

- files/www/cgi-bin/vpn
- files/www/cgi-bin/vpnc
Previous way of retrieving tunnels produced a non-deterministic order. Switch to version with is ordered.
https://github.com/aredn/aredn/issues/283
> Fix tunnel display order

- files/www/cgi-bin/setup
- files/www/cgi-bin/vpn
- files/www/cgi-bin/vpnc
Copy over the perl escapes for the node descriptions and contact information.
The perl code explicitly escapes certain fields and this was not reflected in the lua code - now it is.
Also, fixed a couple of typos.
> Quote escapes (take 2)

- patches/709-iperf-fw-restart.patch
The iperf3 package installs a firewall rule, but the script to restart
the firewall on install had a typo meaning it wasn't called. Instead the
new firewall setup required and otherwise unnecessary reboot.
> Fix typo in iperf fw restart patch.

- files/www/cgi-bin/supporttool
Had to request this file by-hand during the debugging process for some nodes, so add it by default.
This file wasn't included in the old perl version.
> Add /var/run/services_olsr to support tool data

- feeds.conf
received "The unauthenticated git protocol on port 9418 is no longer supported" error.
Changed to https in feeds.conf
> build: github no longer supports the git protocol - use https

- files/etc/config.mesh/aredn
- files/etc/config/system
- files/etc/uci-defaults/95_aredn_migrate_leafletjs
- files/www/cgi-bin/advancedconfig
The old LeafletJS CDN is dead. Migrate to the new approved URL.
Note. I don't know what the old URL did, but the new one, while specified as http:, will direct to https: when
used. Something to be aware of.
> Migrate LeafletJS to new URL

- files/usr/lib/lua/aredn/html.lua
Modify the style sheet URL to let the browser cache while still supporting switching the style.
He old code appended the time which made it simple to switch styles on the node, but forced everyone to reload the stylesheet every time. Now append the actual style after the ? in the url, so we cache the style and let it be switched.
> Modify the style sheet URL to let the browser cache

- files/usr/local/bin/upgrade_prepare.sh
- files/www/cgi-bin/admin
- patches/007-fix-sysupgrade-fail.patch
The old firmware upgrade process attempted to free up RAM by reusing
the 'upgrade_kill_prep' script (which is used internally by '/sbin/sysupgrade').
Unfortuantely this doesn't work as intented. While the script will go about
killing various services, 'procd' just goes and starts them up again using
quite a bit more memory in the process. Instead this script just kills
the various daemons '-9, no questions asked' and then runs the associated
'/etc/init.d/xxx stop' script to instruct 'procd' not the start them up again.
This gets us to the place the original script was trying to go.
Also, an extra syntax fix in '007' patch (need spaces around the [ .. ]) as it was erroring
> Improve the firmware upgrade process

- files/www/cgi-bin/vpn
- files/www/cgi-bin/vpnc
Make sure we copy /etc/config/vtun to /etc/config.mesh/vtun when installing tunnels.
While this copy process happens when tunnels are edited, if we install tunnels and then
leave the page and do something on the setup page, /etc/config/vtun will be lost because
/etc/config.mesh/vtun was never created for 'node-setup' to find and copy.
> Make sure we copy /etc/config/vtun to /etc/config.mesh/vtun when installing tunnels

- files/www/cgi-bin/admin
When uploading a package by hand which depends on an uninstalled system package, unless the packages have been updated since boot, the install will fail. This can be particularly confusing because we persist the downloadable package list across reboots but opkg itself does not keep its internal dependency list. Instead detect the dependency failure, update the package list, and try again.
> Automatically update package dependencies if package install fails

- files/usr/local/bin/manager.lua
- files/usr/local/bin/mgr/periodic.lua
Allows user and/or packages to install cron scripts which will be run approximately every hour, day, or week.
A use for something like this came up while I was looking at the mesh ntpd stuff and I really wanted to a way to
refresh the peer list every now and again. Obviously having a daemon hanging around just to do this is very wasteful.
This is a simple alternative which is already familiar to Debian developers. Script are installed in the relevant /etc/cron.X directory and run on the appropriate schedule.
> Add periodic tasks in the style of cron hourly, daily and weekly scripts

- files/usr/local/bin/mgr/namechange.lua
- files/www/cgi-bin/mesh
Neighbors names can be missing and we were just displaying blanks when this happened. Instead we now display IP addresses (as we should have originally).
Also fixed a few other bugs related to the upkeep of this information.
> Fix displaying "Previous neighbors" with empty hostnames

- files/usr/local/bin/node-setup
If wifi is disabled, we will be using a "fake" device for the meshrf. However, this requires that the
underlying physical device is attached, and this might not be the case on devices with present
multiple ethernets (e.g. eth0 and eth1). Detect this and add an extra Hna4 config to OLSR to allow it to
keep using the wifi_ip even when no physical ethernet is attached.
> Make sure services are published even when no dtd or lan connected.

- files/www/cgi-bin/supporttool
It's seems that OLSRD doesn't always open all the appropriate ports, so it would be good to see when this happens. Not a fix, but helpful.
> Add port dump to supporttool data

- files/usr/local/bin/aredn_postupgrade
- files/usr/local/bin/node-setup
- files/usr/local/bin/wifi-setup
- files/www/cgi-bin/advancedconfig
- files/www/cgi-bin/setup
Support changing the default VLAN tag for the WAN interface.
This comes up a bunch for people running complex networks (I had to buy a switch I use to specifically rewrite the VLAN tag of WANs) and providing this as an advance feature seems useful.
Also, added in a 'reboot' message for changing advance config options which need a reboot.
> Support changing the VLAN tag on WAN

- files/www/cgi-bin/advancedconfig
- files/www/cgi-bin/iperf
(see https://github.com/aredn/aredn/pull/337 for the main discussion)
A super lightweight and simple iperf testing page.
Proposing this as an alternative (and probably better) approach to running an iperf3 server by default. In this case the server is launched on demand when the client needs it. This is similar to iperfspeed but without the sophistication; but still makes a useful testing tool without the constant memory footprint.
```
curl http://<client-node>:8080/cgi-bin/iperf?target=<server-node>
```
> Tiny iperf3 UI [also for discussion]

- files/etc/init.d/vtundsrv
Without active clients the server will fail to start. This is okay, except this
error code causes the package installer to incorrectly report an install problem
requiring an unnecessary reboot.
> Only start vtund server if we have active clients.

- files/www/cgi-bin/iperf
I was modifying the old iperfspeed tool to use this service instead and realized
this was missing for it to work correctly. Command line use (as originally
envisaged) is fine - this is just extra.
I also removed the aredn.html and aredn.http libraries which,
at this point, weren't doing anything (compression was disabled).
> Add cross origin access to remove remote access limitation 04/27/2022

- files/www/cgi-bin/iperf
On slower nodes, iperf will not always startup quickly enough and
then the other end's connection fails. Wait until it's available
before returning (limited to 5 seconds)
> Wait for iperf3 daemon to startup before returning.

- files/etc/config.mesh/aredn
- files/etc/uci-defaults/80_aredn_lqm
- files/usr/local/bin/mgr/lqm.lua
- files/www/cgi-bin/advancedconfig
- files/www/cgi-bin/lqm
Improve Neighbor messaging
Decrease default ping penalty
Only apply ping penalty if we have a good SNR to the other end - avoids problem when nodes are rebooted/upgraded and go away briefly.
> LQM improvements

- files/usr/local/bin/mgr/lqm.lua
Very old APIs don't return link_info, and the code failed to handle this.
> Really old sysinfo.json dont have link_info

- files/usr/local/bin/mgr/lqm.lua
Fix empty initial lqm status.
Limit distance between DtD nodes which are considered at the same site.
Some network setups use non-ham radios to connect nodes over DtD links.
These should not be consider the same site, so we limit how far appart DtDed
nodes can be when optimizing.
> LQM fixes 5

- files/www/cgi-bin/ports
Restarting the firewall removes any LQM information, so restart the manager (LQM is part of the manager) to restore this.
> Restart manager when we restart the firewall

- files/usr/local/bin/mgr/lqm.lua
- files/www/cgi-bin/ports
1. Make user mac filter more tolerant of mac list format
2. Track block state based on actual firewall rules - External actions can change the firewall table (usually clearing and rebuilding it) leaving LQM's idea of what is blocked different from the actual firewall rules. Now use firewall as the LQM state.
> LQM fixes 6

- files/usr/lib/lua/aredn/html.lua
- files/www/cgi-bin/mesh
- files/www/cgi-bin/status
This PR separates the normal alert banner for unsupported hardware (which will appear on every page), so that the AREDN Alert Messages will only appear on the non-protected pages (Status and Mesh).
> restrict msg banner to nonprotected pages

- patches/716-ubnt-pbe-100mb-port.patch
Force device speed to be 100Mbps, but allows it to actively negotiate with the switch. This avoid any extra switch configuration, and is invaluable when the switch is dumb (like the popular outdoor nanoswitches) and cannot be reconfigured.
> Keep 100mb as the only speed, but let the port autonegotiate with the switch

- files/www/cgi-bin/setup
When re-enabling Mesh Wifi with LQM already enabled, there are no parms for LQM set at that moment so don't check them.
> Fix error when re-enabling wifi mesh with lqm on

- files/usr/local/bin/node-setup
- files/usr/local/bin/olsrd-config
The AREDN code now cross references entries in /etc/ethers with those in
/etc/hosts to determine if an IP is #NOPROP. The dnsmasq code could not handle
the #NOPROP flag at the end of /etc/ether entries.
> Remove #NOPROP from /etc/ethers where it was being incorrectly parsed.

- files/usr/local/bin/mgr/lqm.lua
Never block short DtD links regardless of quality.
Ignore invalid mac from arp table when building lookup table.
This avoids a problem where a mac can be in the table twice,
once valid and once invalid with an old ip address.
> DtD detection fixes

- files/www/cgi-bin/setup
Without the -f flag, curl was not reporting a failed update.
Also, made the error message more general as we don't actually know why it failed and "connected to the internet" isn't necessarily right or helpful.
> Stop map update claiming success when it actually fails

- files/usr/local/bin/mgr/lqm.lua
- files/www/cgi-bin/advancedconfig
- files/www/cgi-bin/sysinfo.json
Allow auto-distance to be overridden when LQM cannot determine the distance to other nodes
https://github.com/aredn/aredn/issues/415
> Allow LQM auto-distance to be overridden

- files/www/cgi-bin/setup
Set non-nil default values on one case where it was generating this message "attempt to concatenate global 'wifi2_channel' (a nil value)" and a "Bad Gateway" web page on the Setup display.
Originally posted on the forum here: https://www.arednmesh.org/comment/19713#comment-19713
> set default non-nil values on setup

- files/www/cgi-bin/scan
Reduce the graph colors and add a key to improve the the information being conveyed by the spectral scan. Now we display 3 bands - noise, 95% of traffic, and 5% of traffic. The goal is to convey both where the spectrum is in use, and how much it is in use. Hopefully this does a better job of that.
> Reduce colors and improve scan information

- files/www/cgi-bin/ports
Fix for https://github.com/aredn/aredn/issues/436
> Prevent < and > being used in service names

- files/www/cgi-bin/admin
Allow longer filenames to be displayed after `Choose File` input.  Fixes #434
> allow long filename display

- files/www/cgi-bin/iperf
Sometimes, when an iperf3 server is started for a test, it will bind to an address which isn't the main mesh address. For tcp this isn't a problem as the test is connection based, but for UDP this can cause issues by sending UDP from an unexpected address. By always binding the server to the primary node address we avoid this problem.
I've been chasing this for a while as it's been making automated UDP based testing unreliable.
> Fix random iperf failures

- files/www/cgi-bin/setup
Simplifies the handling of changes to the node and tactical names, rigorously validates the names according to:
- the syntax requirements of RFC 952 as modified by RFC 1123
- the length limit of 63 characters given in RFC 2181
and gives more specific error messages when either name fails validation.
> Fully validate node and tactical names; give better messages when invalid.

- files/www/cgi-bin/advancedconfig
The hAP is the first device to support which also contains a switch chip. In this case it's easy to do as the WAN port is separate from the switched port.
> Add WAN VLAN support to the Mikrotik hAP

- files/usr/local/bin/olsrd-config
- files/www/cgi-bin/admin
1. Add an 'arping' check for an address is a normal ping fails. This uses arp to find an address on the network, and will find devices which are live but have pings blocked. Only works for local lan devices.
2. Feedback from users - After an upgrade, services are left registered even though the packages are not yet reinstalled. We hide these service entries and restore them when the package is installed again - but there was a delay because we only run the check once per hour. It wasn't obvious what was happening, so now we immediately run the check after a package install.
> Improvement to service checking

- files/www/cgi-bin/ports
Based on user feedback, and @ae6xe earlier comments, added some visual feedback when a service is not being published. Some hover text says what's going on, but there probably needs to be some help to explain why this might be happening.
Just reusing a 'dot' asset we already had.
> Add a visual indicator when a service is not being published.

- files/www/cgi-bin/advancedconfig
Put the _Advanced Configuration_ settings in a different order.  Since LQM is enabled by default, those settings could go first, followed by other system settings, with paths and alerts last.
[AB7PA-Hub Advanced Configuration.pdf](https://github.com/aredn/aredn/files/9293416/AB7PA-Hub.Advanced.Configuration.pdf)
> reorder advconfig settings

- files/etc/config.mesh/_setup
- files/etc/config.mesh/_setup.default
- files/etc/hotplug.d/iface/11-meshrouting
- files/etc/local/mesh-firewall/10-lan-to-wan
- files/etc/uci-defaults/81_aredn_migrate_wansettings
- files/usr/lib/lua/aredn/controller/setup_basic.lua
- files/usr/lib/lua/aredn/info.lua
- files/usr/local/bin/aredn_postupgrade
- files/usr/local/bin/mesh-firewall
- files/usr/local/bin/node-setup
- files/www/cgi-bin/advancedconfig
- files/www/cgi-bin/setup
Part 1 - when "Prevent LAN devices from accessing WAN" is enabled, use a firewall rule to prevent traffic from LAN going to the WAN.
Part 2 - we need to change the dialog and the DHCP offerings to allow three cases:
a) LAN can access WAN
b) LAN cannot access WAN (LAN devices get a default route)
c) LAN cannot access WAN (LAN devices dont get a default route)
Option (b) is necessary for devices which dont support DHCP option 121 and 249 .. such as many IP cameras.
Option (c) is what you probably think you have now, you don't because traffic isn't blocked.
Just need some good UX/UI suggestions to finish this up.
Related to:
https://github.com/aredn/aredn/issues/475
https://github.com/aredn/aredn/issues/474
https://github.com/aredn/aredn/issues/26
https://github.com/aredn/aredn/issues/42
> Fixes for "Prevent LAN devices from accessing WAN"

- files/etc/arednsysupgrade.conf
- files/etc/uci-defaults/99_setup_aredn_include
Proposal for a simple way to allow a user to override the default swconfig and keep it across upgrades.
This seems sufficiently specialized that even an advance config is not the way to go; but as you can already
override swconfig if you want, this just provides a mechanism to keep those changes across upgrades.
> A simple way to keep a user swconfig override across upgrades

- files/usr/local/bin/olsrd-config
Hostname is always valid for NAT but is never in the valid_hosts table.
> Dont validate hostname in NAT mode.

- files/www/cgi-bin/admin
Make Support Data download more prominent with a button rather than a link.  Everything else on the page is enabled using buttons, so this makes Support Data consistent with that.
> change support link to button

- files/etc/dnsmasq.conf
- files/usr/lib/lua/aredn/info.lua
- files/usr/local/bin/mgr/namechange.lua
- files/usr/local/bin/olsrd-config
- files/www/cgi-bin/api
- files/www/cgi-bin/mesh
- files/www/cgi-bin/ports
- files/www/cgi-bin/status
- files/www/cgi-bin/supporttool
When the olsr hosts are updated, the file gets truncated which can cause problems for the mesh display.
Here we use the olsrd update notification mechanism to first make a copy of the current hosts_olsr and then atomically move them to the new host_olsr.stable file. This guarantees that the rest of the system never sees a truncated set of hostnames.
> Snapshot hostnames after updates so we have a consistent copy to display

- files/www/cgi-bin/signal
Missed this old "lua version" tag when the others were removed.
> Remove an old "Lua version" display tag

- files/usr/local/bin/mgr/rssi_monitor.lua
The new code was detecting the wifi deadness, but not fixing it. The support tool code did fix the isse. So, let's try using the wifi scan used in the tool (which is active rather than passive).
> Switch to more active wifi reset

- files/usr/local/bin/manager.lua
Garbage collect before we sleep to keep the memory footprint down. We're about to wait anyway, so now is a good time to do this.
> Force a GC before the lua manager sleeps

- files/www/cgi-bin/setup
Found one place where the code still relied on a value being in /etc/config.mesh/_setup when it did not yet exist after a firmware upgrade.  This PR fixes that by relying only on /etc/config.mesh/aredn now.
> fix retrieval of ntp_period

- files/www/cgi-bin/status
Count hosts and nodes using the olsr_host file rather than asking olsrd for some json.
This saves memory (and maybe some time) and gives very similar (but not identical) values. I changed the web page labels to reflect the change.
> Display hosts totals rather than olsr totals

- files/www/cgi-bin/mesh
Freemem was in bytes (not kbytes) and hash removal was broken.
> Fix limiting nr of route shows with low memory

- files/usr/lib/lua/aredn/info.lua
- files/usr/lib/lua/aredn/nettools.lua
- files/usr/lib/lua/aredn/utils.lua
- files/usr/local/bin/manager.lua
- files/usr/local/bin/mgr/fccid.lua
- files/usr/local/bin/mgr/linkled.lua
- files/usr/local/bin/mgr/lqm.lua
- files/usr/local/bin/mgr/namechange.lua
- files/usr/local/bin/mgr/snrlog.lua
- files/usr/local/bin/mgr/watchdog.lua
- files/usr/local/bin/nvram-setup
- files/www/cgi-bin/api
The majority (>95%) of the footprint of lua manager is from loading in external libraries. We can reduce this by not loading
system libraries just for one function, and removing of moving functions from our aredn lua libraries so we load in
less unnecessary code.
These changes drop the active lua manager footprint by 25% and the internal heap usage by 50%.
> Strip out as many dependencies from Lua Manager as possible to save memory

- files/etc/uci-defaults/81_aredn_migrate_wansettings
When wan settings had never been modified, they would be migrated incorrectly.
Thanks to N6HLZ for spotting this.
> Fix migration of wan settings when they've never been modified.

- files/www/cgi-bin/mesh
Accidentally triggered this today, which breaks the mesh display. Ignore these badly formed entries.
> Handle names missing .local.mesh

- files/etc/dnsmasq.conf
The node's limited log buffer is being filled quickly by dnsmasq which is very chatty.  Once the log buffer fills, then older messages are lost when they may be needed.  There seems to be no way to _reduce_ the chattiness of dnsmasq, but there is a way to keep it from logging altogether.  This allows other important messages to be retained for a longer period of time in the log.
> stop dnsmasq from filling the log 11/01/2022

- files/www/cgi-bin/ports
Set some minimum field widths on the **Ports** display. This helps with readability on various web browsers that tend to auto-squash field widths. Tested on chromium, safari, and firefox. Made the DHCP Hostname field a little wider so more characters in longer hostnames can be seen without scrolling right.
> set min field widths on ports page

- files/www/cgi-bin/status
Add the _MemAvailable_ value from `/proc/meminfo` to the **Status** page.  This value is an estimate of how much memory is available for starting new applications. The linux kernel calculates this value from MemFree, SReclaimable, the size of the file LRU lists, and the low watermarks in each zone.  [See this link for more information on MemAvailable](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773).
This PR also removes the buffer cache value from the free memory calculation, which inflates the free memory value (per Joe AE6XE).  It continues to display the sysinfo value for comparison purposes.  It also removes the confusing /tmp free value, since it is not separate storage space but is already included in the …
> add kernel MemAvailable to Status page

- files/etc/local/mesh-firewall/05-xlink
- files/usr/local/bin/mgr/lqm.lua
- files/usr/local/bin/olsrd-config
- files/www/cgi-bin/mesh
Improve integration of external links (xlinks).
These are the extra vlan links, often to non-aredn radios. These changes better integrate the links into the other
subsystems, including how they look on the Mesh page, and allows LQM to monitor them.
> Improve xlink integration

- files/www/help.html
Remove reference to nodes reducing power levels per @ae6xe Joe.
> Re: node may reduce power at higher link rates.  While this behavior is stated in Ubiquiti specifications, I've never seen anything in ath9k or openwrt forums that suggests this occurs in the open source implementations. I'd speculate that open source, and thus AREDN, does not have this behavior. I've also not seen any information of what other vendor's do.
> remove reference to nodes reducing power

- files/www/cgi-bin/status
Add a line showing the WAN wifi SSID and SNR if the node is using its Wifi as WAN connection.
**Here is the Status page with no WAN connection:**
**Here is the Status page with Ethernet WAN connection:**
**Here is the Status page with Wifi WAN connection:**
> add WAN wifi ssid and snr to Status page

- files/www/cgi-bin/status
Based on the suggestion from @ae6xe Joe ([see Issue#553](https://github.com/aredn/aredn/issues/553)) here is a possibility for displaying both types of gateway on the **Node Status** page.  Here are some samples of the display under various conditions.
**Mesh node without WAN connection:**
**Mesh node with wired WAN connection:**
**Node using its radio for Wifi WAN:**
**Dual radio node with Mesh RF and LAN AP:**
> display both types of gateway on Status page

- files/www/cgi-bin/setup
This files doesnt exist when node is installed, cuases a bad gateway failure and stops the node being setup.
> Check /etc/config/vtun exists

- README.md
- SUPPORTED_DEVICES.md
Make it easier to find Supported Devices by separating from the more static README file, making the README file much easier to maintain going forward.
> separate devices from standard README

- files/usr/local/bin/upgrade_prepare.sh
In an attempt to save memory on low memory devices I was killing hostapd early, but that just causes upgrades over wifi to fail completely. So remove this.
> Dont kill hostapd at start of upgrade process.

- patches/750-ibss-2g-fix.patch
- patches/series
There's a bug where 2.4GHz channels will associate incorrectly with other 2.4 channels even though they are on different frequencies. The problem appears to be triggered during scans when scan probes are sent and received on many different frequencies, but are then reported as as they arrive as if they come from the selected frequency of the device, causing incorrect stations to be created. This can only occur for IBSS (adhoc) mode, when the IBSS frequency is fixed, and when the SSID is also fixed. We do all this for AREDN. Fortunately these probe contains (but *only* on 2.4 GHz) the actual frequency of the sending device, so we can avoid incorrectly creating stations which are not really a match. This situation does not seem to happen on 5GHz channels. e Please enter the commit message …
> Fix IBSS problem on 2.4GHz

- patches/702-enable-country-hx.patch
This forces the global and device specific regions to be HX rather than US
> Make the default country HX (HAM)

- files/etc/radios.json
- files/usr/local/bin/mgr/rssi_monitor_ath10k.lua
- files/usr/local/bin/mgr/rssi_monitor_ath9k.lua
- patches/701-extended-spectrum.patch
- patches/750-ibss-2g-fix.patch
This makes -ve channels work on AC devices.
This is not a perfect fix as it can still take an AC device a couple of minutes to connect to an existing network as
the initial scans fail to find it. This can probably be improved so connect is more immediate.
> Enable ac neg channels

- files/usr/local/bin/mgr/lqm.lua
In the latest openwrt, setting dontroute break out tunnel ping checks. As we're forcing the device anyway, we can remove this option.
> Fix tunnel quality measurement

- files/usr/local/bin/mgr/lqm.lua
meshchat uses curl which has much better control over timeouts for bad connections. Nick that code and use it here also.
> lqm: Switch from wget to curl for better control of timeouts

- SUPPORTED_DEVICES.md
Looks like the NAND layout for a few Mikrotik devices has changed sufficiently that they cannot be easily upgrade and must be reinstalled from scratch.  Note this in the SUPPORTED_DEVICES matrix.
> Tag devices which must be reinstalled.

- files/usr/local/bin/mgr/lqm.lua
When a tunnel is idle, binding to the tun* device fails; so remove it. As we have a direct tunnel route in the routing table (not OLSR table 30) created by vtun, we will still correctly route the quality testing traffic.
Validated for both idle and active tunnels.
> Fix idle tunnel quality check 01/07/2023

- files/usr/local/bin/olsrd-config
The connect timeout doest not include DNS lookups, and if DNS is broken this can hang forever. Add a maxmimum timeout so this call will eventually terminate regardless.
> Add a maximum timeout for service checks 01/08/2023

- files/etc/uci-defaults/80_aredn_lqm
- files/usr/local/bin/mgr/lqm.lua
- files/www/cgi-bin/advancedconfig
- files/www/cgi-bin/lqm
A new LQM feature which detects hidden nodes which a node cannot see directly and display them as part of the LQM information. It can also (but is off by default) enable RTS/CTS to improve quality by reducing transmission failures when hidden nodes are detected.
RTS/CTS mitigation is off by default, even when hidden nodes are detected. But when it's enabled I've been able to do a little testing locally on a few Omni's we have locally, and its reduced transmission failures from 30% to about 8%. I would expect more, but in my test only a single Omni was using RTS/CTS while all its neighbors were not.
> Hidden node detection (and optional mitigation) 01/12/2023

- files/www/cgi-bin/admin
You cant (easily and reliably) go back once upgrading this time, so block older firmware versions from being offered.
> Block older versions of the firmware once we upgrade

- files/etc/uci-defaults/12_mikrotik_boot
https://github.com/aredn/aredn/issues/633
Reports that the hAP AC2 will fail to boot when the WAN cable is connected. This does not effect all devices. However, I've also seen this on my hAP Lite device and it is not a new problem (as long as I've owned it!). The forum post below indicates the boot loader can be set to the wrong mode, causing the device to lockup sometimes when booting. Checking my two hAP AC2, they were both in different modes. It looks like it might be possible to accidentally change this mode by holding the reset button for different periods of time when powering on the device. This might explain why some nodes have this problem and some don't.
See: https://forum.openwrt.org/t/openwrt-installed-mikrotik-rb750gr3-wont-boot-when-wan-cable-plugged/146330/7
> Mikrotik boot loader change to avoid boot lockup problem

- files/etc/uci-defaults/80_aredn_lqm
- files/usr/local/bin/mgr/lqm.lua
- files/www/cgi-bin/advancedconfig
As we though this was on anyway, I'd say we should enable RTS whenever we detected hidden nodes in order to establish a more reliable network. It can still be disabled in the advanced settings.
Thoughts?
> Automatically enable RTS when hidden nodes detected

- configs/common.config
Package provides kernel driver for I2C RTC modules such as the DS3231.
Ref #152 #153
This was dropped in the OpenWRT upgrade
> Re-enable kmod-rtc-ds1307 package 01/27/2023

- files/www/cgi-bin/iperf
This cryptic bit of shell script adds a maximum timeout for the iperf client to run as it appears it can get stuck occasionally. The server has a built-in timeout (not available in client mode)
> Provide a timeout on the iperf client.

- files/usr/local/bin/mgr/lqm.lua
Very occasionally I'm seeing ARP entries for IP addresses which are not routable. These always seem to be for the IP address of a device with mesh RF disabled. It's not clear how this can happen as this IP is not assigned to the DtD VLAN which is how they're being reported in the ARP cache. Also, this problem shows up in both the current release and the nightlies. It doesn't effect the routing on the node (the routing table is correct) so these "bad" arp entries never cause anyone but LQM a problem. This change stops LQM being confused by them.
> Filter out non-routable ARP entries which confuse LQM

- SUPPORTED_DEVICES.md
Some things are excluded from tiny builds to make the install image small enough.
> Tiny build notes 02/03/2023

- files/usr/local/bin/node-setup
Provide <INTERFACE_mac> variables for network overrides - a more flexible way than using the 'include' mechanism for this.
> More consistant way to provide interface mac address in overrides

- files/usr/lib/lua/aredn/utils.lua
Instead of manually parsing query strings by splitting on & and =, use the already-provided luci.http.urldecode_params() to do it correctly. As a side effect, this will also properly handle url-encoded parameters.
For example:
http://localnode/cgi-bin/api?status=olsr,alerts
vs
http://localnode/cgi-bin/api?status=olsr%2Calerts
```json
$ GET 'http://localnode/cgi-bin/api?status=olsr%2Calerts'
{
"pages": {
"status": {
"alerts": {
"aredn": "",
"local": ""
},
"olsr": {
"nodes": "356",
"entries": "1257"
}
}
},
"api_version": "1.5"
}
```
Fixes #702
> Use luci's urldecode_params to handle query string

- files/usr/local/bin/mgr/snrlog.lua
- files/www/cgi-bin/signal
It could cause multiple entries for nodes with different name cases.
> Normalize the case of the macs and node names

- files/usr/local/bin/mgr/lqm.lua
Improve the way LQM manages the distance, and therefore the wifi coverage.
Some devices, notably AC devices, seem much more sensible to accurate distance settings. This means we need an improved approach to managing the coverage when adding new devices to an existing set, particularly in PtoMP situations. Now, when new devices are added but distances not yet known, we assume the worst (the maximum allowed distance configured in settings) until we have better information. This avoid cutting of devices which are added but much further away than the current "flock". The downside is that, until the pending distance is measured, bandwidth on error prone channels with be slightly impaired as retransmissions will slightly delayed.
> Improve LQM distance management 02/11/2023

- files/etc/uci-defaults/80_aredn_lqm
- files/usr/local/bin/mgr/lqm.lua
- files/www/cgi-bin/advancedconfig
On the Rocket 5AC Lite if we enable RTS the device fails to send packets.
At the moment we dont understand why or what devices are effected (non-AC devices seem fine).
But disable for every device for now while a solution is found.
> Disable RTS by default in ath10k devices 02/11/2023

- files/usr/local/bin/mgr/lqm.lua
- patches/742-5-and-10mhz-ath10k-ct-support.patch
For some reason, there was code in the driver to block the setting of the coverage when a previous setting wasn't a particular value - a value set by the same code!! It's unclear what this was trying to achieve or prevent, but it stopped AC devices operating efficiently (by a factor of 10x or more).
The coverage being wrong had the knock on effect of breaking RTS because the driver wasn't waiting the correct time when using the protocol.
> Fix AC coverage calculation in driver. 02/12/2023

- files/usr/local/bin/mgr/lqm.lua
- files/www/cgi-bin/mesh
Fix scaling the bandwidth reporting in LQM and for ath10k devices in the mesh page.
> Fix the bandwidth reporting for ath10k devices

- files/usr/local/bin/mgr/namechange.lua
- files/usr/local/bin/olsrd-config
- files/usr/local/bin/olsrd-namechange
On small networks there are not a lot of OLSR name changes. While dnsmasq watches for changes and updates itself, it will sometimes miss them. On busy networks this doesnt matter as the next change will catch it up. But on smaller network (esp. test networks) a missed change can stop name resolution working for some time. So now, if no changes are detected for > 60 seconds, we force dnsmasq to reload its tables.
> Force dnsmasq to update itself if no network changes for > 60secs

- files/usr/local/bin/mgr/lqm.lua
- files/www/cgi-bin/mesh
To follows https://github.com/aredn/aredn/pull/712
Calculate the tx rate the same way for both ath9k and ath10k drivers so we have consistent reporting.
> Ath9k - no error accounting

- files/usr/local/bin/mgr/lqm.lua
When the counters were removed from the rules, the drop checks were not updated and so were failing.
This means we got *thousands* of rules in the firewall table which, eventually, slows everything down.
> Fix rule checking for existing drop rules.

- files/www/cgi-bin/setup
AP radio isn't always phy1 so handle these cases.
Add in some labels to RF and AP for which bands are in use.
> More fixes for AP mode

- files/www/cgi-bin/setup
The WAN Wifi Client password is currently limited to zero characters (for connecting to an open AP) or between 8 and 64 characters.  Unfortunately the node owner has no control over the number of characters in the key for the Wifi AP he is using.  This situation occurs fairly frequently when using a travel node at a hotel.  Chuck NC8Q just ran into the issue at a Country Inn and Suites in Fredericksburg VA where the key was only 7 characters in length.  As an upper limit hopefully 64 characters will be enough, but this PR removes the lower limit on the number of characters allowed for the WAN Wifi AP key.
> remove WAN Wifi Client key lower limit

- files/www/cgi-bin/setup
When re-enabling the mesh radio, the phy will be nil at that moment (but not after a refresh) - handle this case.
> Fix AP mode selection when turning mesh back on.

- files/usr/local/bin/aredn_sysupgrade
- files/usr/local/bin/firmwarecheck.sh
- files/www/cgi-bin/admin
- files/www/cgi-bin/advancedconfig
This has come up a few times as people have started to use nightlies and have ended up on the wrong one (having assuming they should continue to use an incorrect model version because that's what they use to do). The fix is to allow technically incompatible upgrades - technically because they might be perfectly valid .. but there's no easy way to know. So, here's a mechanism which requires a push of a button in the advanced configure, and show a big red banner in the firmware upgrade UI. The trade off here is that providing this mechanism with large red warnings will be less of a support problem compared to people using this to shoot themselves in the foot.
UI for setting the option:
Banner show when option is set:
> Support forced upgrades

- files/usr/local/bin/olsrd-config
- files/www/cgi-bin/ports
Maintain state on when addresses and services have been seen and only disable them if they've not passed validation for a period of time. As configured here, a service would need to fail 3 times in a row over 2 hours before the advert is removed. The advert is always restore if a service later passes the test (just as before).
The goals is to avoid disable advert for services which might occasionally fail or be briefly offline, but just get unlucky with the validation test.
> Validate state of services over a period of time before disabling advertisements

- files/www/cgi-bin/mesh
When people are using the filters on the mesh page, they sometimes hit RETURN. This submit the page (which is a form) causing the page to reload, lossing the filter, and as a side effect, setting the page to auto-refresh.
> Stop RETURN from refreshing the mesh page 03/16/2023

- files/usr/lib/lua/aredn/utils.lua
Unlike any other /X suffix, the /32 is omitted when turned into a string.
> Improve ipFromCIDR function to handle /32 cidrs.

- SUPPORTED_DEVICES.md
I re-did the mikrotik section of the supported devices list
I changed the device column to be the "pretty name" of the product
I changed the SKU column to be the model number of the product
all names and skus are copy and pasted from mikrotik.com/hardware so that it is really easy to double click, right click, search with google, to find a part to buy
ps let me know if you like how I handled the bare routerboard vs basebox vs mantbox or if you think I should change it
> redo MikroTik supported_devices.md

- files/usr/local/bin/mgr/station_monitor.lua
Mikrotik AC devices get into a state where they wont communicate with non-AC devices .. sometimes. Leaving and rejoining the network resets everything. We monitor for this situation and rejoin the network when detected to resolve the issue.
Diagnosis:
It looks like somewhere in the Mikrotik AC firmware, devices broadcast their beacons with an incorrect channel width. This will then confuse devices connecting to them resulting in failed communications. The situation is very intermittent and not all devices seem to be effected, and not every time even if they are.
I'm trying to detect the issue using the arping process as before. This is imperfect as devices sometimes dont answer (wifi broadcasts are unreliable) so I'm looking for failures over time before leaving and rejoining the IBSS …
> Resolve unresponsive node problems with Mikrotik AC devices.

- files/usr/local/bin/mgr/station_monitor.lua
Weak connection which aren't being used can look like faulty connections. We use LQM information to ignore these and avoid false rejoin events which degrade the network.
> Eliminate false network rejoins using LQM information

- SUPPORTED_DEVICES.md
By installing the referenced package on 3.22.12.0 (and maybe earlier ... I've only verified this one) you can do the upgrade to 3.23.4.0 on the BaseBox5 and QRT5. Previously these needed to be re-installed from scratch.
> Note devices which support the danger-upgrade process

- files/usr/lib/lua/aredn/hardware.lua
- files/www/cgi-bin/status
Thanks to @pmilazzo for helping debug this.
> Fix frequency range reporting and display for 900MHz & 3GHz devices

- openwrt.mk
Smoke tested on my bank of 20 nodes without issue. Not sure there's anything material in this update for us.
> Upgrade to OpenWRT 22.03.5

- files/etc/mesh-release
- files/www/cgi-bin/setup
Disable/enabling mesh wifi on multi-radio devices could confuse the allocation of the radios to specific tasks. This was because it was always allocating wlan0 when re-enabling, and this isn't always correct on multi-radio devices.
https://github.com/aredn/aredn/issues/825
> Fix wifi setup for multi-radio devices

- patches/746-rocket-m-xw-support.patch
- patches/748-powerbeam-m5-300-support.patch
This was preventing the currently installed Rocket M5s from finding updates.
> Revert the Rocket M5 filename change.

- files/etc/httpd.conf
- files/usr/lib/lua/aredn/nav/admin/65advancednetwork.lua
- files/www/cgi-bin/advancedconfig
- files/www/cgi-bin/advancednetwork
Proposing a new "Advanced Network" tab on supported devices (although I'm aware this is adding complexity). This provide UI access to features already available by editing configuration files. Two features are surfaced:
1. The ability to reassign the default purpose of the standard ports on supported multi-port devices.
2. The ability to create xlinks (vlans which act like vlan2) which we're using for wiring up backbone links in AREDN networks.
These features are currently supported by installing a seperate package, and we can continue to do that if people prefer, but I thought it might be a more generally useful feature to expose.
Visually, it looks like this:
Currently supported on the hAP ac2 and hAP ac3.
> Advanced networking tab

- files/www/cgi-bin/advancednetwork
Lua confuses empty objects and empty arrays when converting to JSON.
Problem was observed by @ab7pa when editing port assignments.
> Fix lua converting empty port object to empty array.

- files/usr/lib/lua/aredn/hardware.lua
/sys/kernel/debug/ieee80211 can exist without entries sometimes
> Fix 'has_wifi' detection.

- files/usr/local/bin/mgr/rssi_monitor_ath10k.lua
- patches/742-5-and-10mhz-ath10k-ct-support.patch
We had removed one of the two coverage checks which prevents ath10k nodes working at large distances. Now remove the second test which is being triggered in some circumstances. I *think* it is unnecessarily restrictive for our use case. Removing it wont make things worse.
> Remove another coverage test which causes problems.

- files/usr/local/bin/node-setup
- files/www/cgi-bin/advancedconfig
We've found that some nodes which will barely operate with the default MTU will operate very well if it's reduced.
This change provides an advanced settings option to allow users to tweak this.
> Allow MTU on wifi interface to be modified.

- files/usr/local/bin/node-setup
When uci:get(...) fails it return 2 arguments not 1, and that messes up tonumber(...) so we have to do this as two steps.
> Fix MTU failure which broken node-setup

- patches/100-remove-rcbutton-reset.patch
- patches/series
OpenWRT's reset button handler was overriding ours, so remove it.
https://github.com/aredn/aredn/issues/869
> Re-enable AREDN's reset button behaviour

- files/usr/local/bin/nvram-setup
- files/www/cgi-bin/status
On older the hap ac lite the first install now tries to dynamically determine things about the radios which it can't do in this state because the ram image is missing some things by default and the ac radio is not active.
Various fixes to allow for this while running the ram image.
> Fix Mikrotik first instal

- files/usr/local/bin/aredn_message.sh
- files/www/cgi-bin/advancedconfig
These changes are to address the feature request that I put forward in #872. 
At this point the changes are untested, but they appear that they would work. If it is possible to build an AREDN firmware from this branch, then I would be very happy to test the changes on one of my nodes to validate that the functionality is working.
> Added support for group alert messages

- files/usr/local/bin/aredn_message.sh
local_message file should be initialized each time the script is run, or stale messages could be retained.
> fix local message refresh

- patches/010-lz77-decompression-support.patch
- patches/series
Let's try this again.
This patch add LZ77 decompression for newer Mikrotik devices. People are seeing newly bought Mikrotik devices fail to boot AREDN because the wifi wont startup up. This is because Mikrotik is using a new compression scheme which OpenWRT doesnt yet support (so neither do we). Fortunately @SCWhite found a patch written by @john-tho which adds support for some new Mikrotik devices. I generalized it for all Mikrotik (which wasn't very hard) as we're seeing it in older and newer hardware.
The first attempt at this change cause a couple of us to have HAP ac3 devices fail after the upgrade. It remains unclear why that happened as I've been unable to reproduce it again. This version has been tested on my entire bench of devices (24 of various makes and ages) including a power …
> LZ77 firmware decompression for new Mikrotik devices

- files/etc/arednsysupgrade.conf
- files/etc/cron.boot/reinstall-packages
- files/www/cgi-bin/admin
Remember what packages get installed by the user, and reinstall them on the next firmware upgrades.
Locally installed packages are stored and moved across with the upgrade.
It waits a couple of minutes after the upgrade to activate (so the network should have stablised).
Would be good to get some eyes on this to see how reliable it is.
> Remember and reinstall packages after firmware upgrade

- SUPPORTED_DEVICES.md
Previously undefined status of "unknown" was changed to the existing defined status of "untested."  _Sunset_ devices are grouped together, and _Stability_ and _Status_ definitions are moved to top for clarity
> add new wording for devices no longer recommended

- files/etc/config.mesh/dhcp
- files/etc/init.d/local-early
- files/usr/local/bin/node-setup
- files/usr/local/bin/olsrd-namechange
- files/www/cgi-bin/ports
Allow a node to specify a wildcard (starting with *.) subdomain as a DNS alias. DNS request for this subdomain will be delegated to the alias IP address.
> Support wildcard DNS subdomains

- files/usr/local/bin/node-setup
Avoids running this twice after initial supernode change
> Read supernode status from /etc/config.mesh

- files/usr/lib/lua/aredn/olsr.lua
- files/www/cgi-bin/api
getServicesByNode is only a dummy method.
getServicesByService doesn't even exist.
Remove the last remaining references to them from cgi-bin/api, and remove the last traces of getServicesByNode from aredn/olsr.lua
Fixes #948
Fixes #949
> Remove vestigial getServicesBy* methods

- files/usr/local/bin/mgr/aredn_message.lua
- files/www/cgi-bin/advancedconfig
Change AAM default polling interval to once every hour.  This makes AAM a little more useful from an operational perspective.
> change pollrate default to one hour

- patches/749-ubiquiti-firmware-version.patch
- patches/series
Newer LiteBeam hardware wont downgrade lower than 8.7.4, so tweak the LiteBeam config to allow this firmware to install on 8.7.4
This might be safe for other hardware, but it's only tested on LiteBeams so far.
> Bump Ubiquiti version number for LiteBeam 5AC

- files/www/cgi-bin/scan
Some hardware doesnt scan all the frequencies we want by default.
Not a fix for the scan issue seen on some AC devices.
> Use frequency list for scan.

- files/www/cgi-bin/advancedconfig
x86 does not use overlayfs so cannot be restored to first boot. Detect devices which dont use overlayfs and dont show the button.
> Detect if we support firstboot mode

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/new_hardware_support.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
When opening a new issue or pull request, templates will be provided that can be filled in.
In the case of Issues, 4 options will be given for a template to start with (bug report, feature/enhancement request, new hardware support, and general question), as well as an option for a blank issue. Choosing one of the template will automatically tag the issue. To see what this looks like, you can go here:
https://github.com/BKasin/aredn/issues/new/choose
> Add github templates for issues and PRs

- files/etc/config.mesh/network
Added a comment at the top of /etc/config.mesh/network to inform node admins how to override the network configuration for unusual and unique network configurations. See issue #995 for explanation of when overrides may be useful.
#995 
Please also include links relevant to the changes.
> Add comment for overriding network configuation

- .circleci/config.yml
Until we update the docker build image, remove the x86 build
> Temporarily remove x86 nightly build so we can build a nightly again

- configs/ath79-mikrotik-ath10k.config
- patches/744-dd-wrt-firmware.patch
Investigating problems with Ubiquiti devices not connecting. Switch to Ubiquiti firmware rather than third-party.
> Switch to first party Ubiquiti firmware

- files/www/cgi-bin/admin
Because we want to kill the dnsmasq server to save memory when downloading firmware, we should
resolve the download server IP by hand before killing it.
Switch to using curl so we can send the Host: header.
> Resolve download server ip by hand before download

- files/usr/local/bin/node-setup
Had attempted to optimize restarting olsrd by putting more tunnel devices in the config file by default. Unfortunately, olsrd can't cope with too many and performs poorly creating problems on older hardware.
> Reduce tunnels in olsrd to minimum

- files/etc/config.mesh/aredn
- files/etc/uci-defaults/90_aredn_default_tunnels
- files/usr/local/bin/node-setup
- files/www/cgi-bin/advancedconfig
- files/www/cgi-bin/vpn
- files/www/cgi-bin/vpnc
Remove the need to set the maximum number of tunnels a node supports.
We now determine this dynamically for both old vtun tunnels as well as new wireguard tunnels.
> Remove fixed tunnel limits

- .circleci/config.yml
The arednmesh/builder Docker image has been fixed to support building x86.
> Restore x86/64 nightly build

- files/usr/local/bin/manager.lua
Clock changes could cause this to terminate prematurely.
> Improve 'wait_for_ticks' handling of system clock changes

- files/usr/local/bin/manager.lua
- files/usr/local/bin/mgr/hw_watchdog.lua
- files/usr/local/bin/mgr/lqm.lua
Unfortunately there doesnt appear to be much flexibility in the various hardware watchdogs on radios, so setting the watchdog > 60 seconds mostly doesnt work. So rework the settings to allow for this and that our watchdog tests must be frequent and quick. It makes it less configurable and care needs to be taken when selecting ping targets (short timeouts)
> Simply the watchdog by fixing various timeouts.

- files/www/cgi-bin/advancednetwork
The Advanced Network tab was blank for the GL-B1300 because of a missing entry in the layouts table.
Also, while not required, to maintain consistency between the tables, I also added the missing default_configs table entry for the VMware Virtual Platform.
- Add missing layouts table entry for the GL-B1300.
- Add missing default_configs table entry for VMware Virtual Platform
Describe the goals that the pull request accomplishes.
If there are related issues, please link them here.
Please also include links relevant to the changes.
If applicable, please include screenshots before and after your changes.
Add any other context about the problem or changes here.
> Add missing table entries in the Advanced Network tab

- .circleci/config.yml
This uses a script on our build host to do the actual posting.
I don't have access to CircleCI to do it from there :-(
> Post a message to slack after a successful nightly build.

- files/usr/local/bin/node-setup
Not sure how non-uppercase names make it into the /etc/config.mesh/vtun file, but make sure they are definitely uppercase when they're active.
> Make sure the node nodes we use for tunnels are always uppercase

- files/etc/cron.hourly/check-services
- files/usr/local/bin/restart-services.sh
Fix the way we detect changes in reachable hostnames.
The old code was written when hostnames were managed differently in olsrd. This is now a lot simpler.
> Fix host checking

- files/www/cgi-bin/admin
We often see failed downloads of the firmware lists. It's usually nightly which just happens to be the first in the list. So retry failures a couple of times.
> Retry failed firmware version downloads

- files/etc/antennas.json
- files/etc/radios.json
Added antennas to Ubiquiti NanoBridge M5 to get gain and beamwidth info
[Datasheet](https://dl.ubnt.com/nb5_datasheet)
[Antenna Info](https://dl.ubnt.com/UBNT-AOS_prod-specs-rf_3.pdf)
None
The NanoBridge M5 comes in 2 versions with different dishes, but both use the same radio and will show as the same hardware.
Added antennas to combat this issue.
> Added antennas to Ubiquiti NanoBridge M5

- files/www/cgi-bin/advancednetwork
Support dynamic number of ethernet devices in VMs.
Note that decreasing the number of ethernet devices after a configuration has been setup to use them will probably have unintended consequences.
Unknown how well this will play with custom configurations some people are using.
> Support dynamic number of ethernet ports on VMs

- files/usr/local/bin/mgr/lqm.lua
Update cursors on each lqm iteration.
If we dont, and other apps change values in the config files, old cursors dont see the changes.
> Update cursors on each lqm iteration.

- files/etc/radios.json
Added external antenna to boardID `0xe2b5`
Renamed board `Ubiquiti NanoBridge M5 (XM)` to reflect info from support file
None
Overlooked this board ID in previous PR #1065
> Added external antenna and (XM) destinction to boardID 0xe2b5

- files/www/cgi-bin/mesh
Alphabetically sort node with the same ETX so the list doesnt jump around as much
> Sort node list in mesh display

- files/etc/config.mesh/network
- files/usr/local/bin/node-setup
When including user network override data, validate it first so we dont generate broken /etc/config files and make the node unbootable.
> Validate network override configs

- files/www/cgi-bin/vpn
If we change the name associated with a wireguard tunnel, we generate a new key.
We do this so that, when reusing a tunnel entry, we start with a fresh key otherwise they
old key, which is still out there, could be reused causing problems.
> Regenerate key when client name changes

- SUPPORTED_DEVICES.md
add x86 to supported devices list as a unsupported device - mainly to add clarity on images / tested configs.
Adds clarity/documentation of x86 images and what it's been tested on.  Lists images as unsupported.
https://github.com/aredn/documentation/pull/336
#1089 
n/a
As a part of a bug I found in #1089  I wanted to make it a bit easier for people to build VMs, as I had some issues. This also helps new supernode owners who are setting up VM for this in datacenters etc.
> Add x86 to SUPPORTED_DEVICES.md

- files/www/cgi-bin/iperf
This is a workaround for a bug where iperf3 will just block randomly and no longer send data during a test (most often at the end).
It may effect the absolute performance measurements compared to the default buffer value although I didnt see that in my testing.
> Limit buffer size of iperf3 test to 1K

- files/usr/lib/lua/aredn/nav/admin/65advancednetwork.lua
- files/www/cgi-bin/advancedconfig
- files/www/cgi-bin/advancednetwork
I forgot we need DSA support to have xlinks, and the old hap doesnt have it.
> Revert hAP AC Lite xlink support

- files/usr/lib/lua/aredn/nav/admin/65advancednetwork.lua
- files/usr/local/bin/node-setup
- files/www/cgi-bin/advancedconfig
- files/www/cgi-bin/advancednetwork
Xlink had originally been envisaged as a point-to-point connection
leaving the "how" of that to other hardware and software. However, there's a use case
where the non-AREDN radios in the xlink need to be accessed, and allocating
addresses within the xlink's address range is a good way to do that.
By supporting a subnet on a xlink we can enable this.
> Support CIDR (e.g. /24, /16, etc) on a xlink

- files/www/cgi-bin/supporttool
Include tunnels in the support tool data dump, but hide the passwords they contain.
Also rename support tool data to include the .tar (as that's what it is).
> Include tunnel information in support tool dump (with hidden passwords)

- files/www/cgi-bin/mesh
Restructure the way the mesh page is built so we can search and filter better.
Before, when an entry was found in a search, the whole node entry had to be displayed, including all the stuff which didnt match the search.  By restructuring how the page is built, we can only show the lines of a node which actually match the search, making it cleaner and easier to see what you were looking for.
> Improve mesh page searching

- files/www/cgi-bin/mesh
The auto refresh option on the mesh page previous created a file on the node so that everyone would be affected and it would persist. This never seemed to be what people want, so instead the auto refresh is now per browser page.
> Make auto mesh reloading per browser rather then per node

- files/usr/lib/lua/aredn/html.lua
- files/www/cgi-bin/admin
- files/www/cgi-bin/advancedconfig
- files/www/cgi-bin/advancednetwork
- files/www/cgi-bin/setup
- files/www/cgi-bin/vpn
- files/www/cgi-bin/vpnc
Rather than using a reload meta tag with a fixed timeout, use a bit of javascript to check for when a node has rebooted successfully, and then reload the page. This should help things be more timely and result in less reload failures.
> Use adaptive reload mechanism when node upgrades or reboots

- files/usr/local/bin/mgr/lqm.lua
Too many retries appears to cause network congestion issues slowing down links with multiple hops, but reducing this to 1 then caused single links to have poor performance. Try a retry of 2 as a better compromise.
> Set pkt retry to 2 (was 1) for hub nodes.

- files/usr/local/bin/nvram-setup
On some devices the hardware MAC for the WLAN and ETH are the
same so the 10.DTD and 10.WLAN addresses are identical.
If we detect this, bump the DTD address.
Commonly seen on TP-Link devices (but there are others)
> Fix DTD and WLAN ips derived from matching MACs.

- files/etc/config.mesh/olsrd
- files/usr/local/bin/node-setup
Double various OLSR traffic intervals to half the maintenance traffic.
Our network isn't very mobile, so reducing this traffic should not result in a less stable mesh.
Might be able to do more here, but starting with this reduction.
Timeouts remain unchanged.
> Half the OLSR maintenance traffic

- files/usr/lib/lua/aredn/olsr.lua
- files/www/cgi-bin/mesh
The old attempt to fix the occasional missing hosts on the mesh page wasnt working so let's try something new.
This time we re-read the hosts_olsr file if we fail to open it.
> Fix missing hosts on mesh page

- patches/709-iperf-fw-restart.patch
This patch had to be fixed on every openwrt upgrade just because the version number would change. We dont
do this with other packages so stop doing it here.
> Stop messing with the iperf3 package version number

- files/usr/lib/lua/aredn/html.lua
- files/usr/lib/lua/aredn/http.lua
- files/www/cgi-bin/admin
During the initial setup the IP address of the node can move around a fair bit. 
Make sure the reboot timeout code handles this.
> Improve the reboot/flash timers

- files/usr/lib/lua/aredn/html.lua
- files/www/cgi-bin/admin
When rebooting or reflashing the node, display a progress bar as
well as the estimated time remaining. Also, show the time remaining
in MM:SS format.
> Show progress bar during reboot/reflash and show estimated time remaining in MM:SS.

- files/www/cgi-bin/scan
Cache the last wifi scan and update it when a re-scan is requested. This change was suggested as a way of handling Ubiquiti AC devices which disconnect while scanning and making retrieving the results problematic if that was your connection. Now we scan and store the results so they can be retrieved later. In fact we no longer scan when navigating to this page show the last scan and a time stamp.  To update the scan push the rescan button. This make the page generally more responsive when initially navigated to.
> Scan cache

- files/www/cgi-bin/setup
Make sure dmz_dhcp_end has a value, even in NAT mode. The value is lost (set to "") in the config because in NAT mode it's not important. However later code still does math with it, so give it a sensible value here to avoid problems later.
> Make sure dmz_dhcp_end has a value, even in NAT mode

- files/usr/local/bin/node-setup
Access didnt change without a reboot - now it does.
> Fix restarting firewall when wan telnet/ssh/web access changes

- files/usr/local/bin/mgr/lqm.lua
- files/www/cgi-bin/lqm
- files/www/cgi-bin/mesh
This includes some extensive improvements and changes to LQM. There are associated changes in aredn_packages to sync with this.
1. The tracking state has been cleaned up so each tracker only contains valid state for what's being tracked. Before there were lots of "defaults" which weren't valid.
2. LQM now tracks rolling averages of tranmission traffic, retries and failures.
3. LQM will always run *even when disabled*. When disabled, LQM will not apply any changes to your system, but it will still track all the state so it's available as metrics for monitoring.
4. Blocking has been reworked to be cleaner and easier to understand. Functionally it behaves the same, but there was some ambiguity in the handling of explicit user blocks which has been resolved.
5. Polling remote state has been …
> LQM improvements.

- files/usr/local/bin/node-setup
- files/www/cgi-bin/ports
- The "Always" checkbox now works for options with an explicit tag, and is disabled for untagged options; the latter cannot be supported because of a limitation in the OpwnWRT configuration language.
- Tagging by host name has been removed; it didn't work before and isn't particularly useful in the AREDN context.
- Tagging by Agent Circuit ID, Agent Remote ID, and Subscriber-ID are now supported so that a DHCP Relay Agent can be used to extend the LAN across multiple subnets.
- Small improvements were made to error handling and hints.
> Improvements and fixes for Advanced DHCP Options

- files/www/cgi-bin/ports
DNS aliases support a prefixed wildcard but the validation pattern did not - fixed.
> Fix dns alias validation pattern to allow wildcard DNS again.

- files/etc/config.mesh/dhcp
Every node starts DHCP on the LAN interface and we rely on this behavior, but without this option it wont happen.
> DHCP was not always starting on the lan interface like we need it to.

- files/usr/local/bin/mgr/lqm.lua
- files/www/cgi-bin/mesh
To avoid cutting off poorly performing leaf nodes we now try to identify them and, even if they fail the SNR and Quality test, dont block them. In this case we also avoid from using unicast OLSR traffic as these poor links would increase the retry traffic and potentially saturate the radio.  Links which trigger these conditions are marked in the UI so people are aware.
This doesnt solve a link's performance problem, and supporting them will impact other links by taking time on the radio away from them, but we want to avoid cutting off leaf nodes if possible.
> Avoid cutting off leaf nodes

- files/usr/local/bin/mgr/lqm.lua
- files/usr/local/bin/mgr/wireless_monitor.lua
Wireless monitor runs an emergency wifi scan at 3am to recover forgotten nodes.
LQM no longer tries to ping stations which have disconnected.
> Wireless monitoring improvements

- files/etc/uci-defaults/80_aredn_lqm
We calculate quality differently (ie. correctly) so drop the default minimum to avoid too many nasty surprises.
> Lower default quality

- Makefile
- files/www/cgi-bin/admin
- patches/610-mikrotik-sysupgrade-v7.patch
- patches/series
Some Mikrotik devices can no longer be downgraded to v6. Add support for v7 bootloaders.
This requires a new sysupgrade-v7 file format.
> Mikrotik bootloader v7 support

- files/app/main/status/e/tunnels.ut
https://github.com/aredn/aredn/issues/1266
urlencoded arguments can be no longer than 4K. With large numbers of tunnels this limit was exceeded causing failures. Break up the argument into individual tunnels instead.
> Fix problems with large numbers of tunnels

- files/usr/lib/lua/aredn/services.lua
Because firewall redirect only effect incoming traffic to the node, locally generated traffic (such as from the service checker) wont follow them.  Do them by hand.
> Fix nat service validation

- files/usr/lib/lua/aredn/hardware.lua
- files/usr/local/bin/mgr/gps.lua
5 decimal places is good enough, although the hardware reports more.
There *may* be a Lua bug related to excessive precision numbers in certain trig functions, so this avoids that also.
> Limit reported GPS precision

- files/app/main/firstuse-ram.ut
- files/app/main/firstuse.ut
- files/app/root.ut
Unless device is unconfigured, dont let the first use pages do anything.
> Lockdown first usage pages.

- files/app/main/status/e/firmware.ut
Use less space to show the current firmware and hardware info.
https://github.com/aredn/aredn/issues/1296
https://github.com/aredn/aredn/issues/1343
> Compact the firmware+hardware info in the dialog

- files/app/partial/tools.ut
Matches old UIs support. Might look at extending this later.
> Wifi scan is only available in mesh mode

- files/app/main/status/e/dhcp.ut
- files/app/main/status/e/internal-services.ut
- Fix spellings of suboptions and their keys.
- Do not drop leading spaces, so options with no tag will work.
- Do not drop trailing spaces, which may be required in tag patterns.
- Fix regular expressions to handle embedded spaces in options and tag patterns.
- Handle special characters in tag patterns (primarily for Subscriber-ID).
>  Fix parsing by new UI of advanced-DHCP-option configuration files.

- files/app/main/status/e/firmware.ut
- files/usr/share/ucode/aredn/hardware.uc
The Mikrotik hAP ac3 can install the usual sys image with either the v6 or v7 bootloader. NAND devices are just different I guess.
> Exclude the Mikrotik hAP ac3 from the v7 check (it doesnt use it)

- files/app/main/status/e/dhcp.ut
- files/app/main/status/e/local-services.ut
- files/app/main/status/e/ports-and-xlinks.ut
- files/app/main/status/e/tunnels.ut
When we add new ports, services, xlink or tunnels, move the focus automatically to the first field of the new item.
> Focus newly created items

- files/app/partial/packages.ut
- files/etc/cron.boot/reinstall-packages
The UI uses opkg to check package status which can cause a lock clash if the reinstall script is running. Retry opkg commands in the script if this happens, and also avoid reading package status in the UI until the reinstall is complete.
> Manage lock clash when reinstalling packages.

- files/app/main/status/e/time.ut
- files/etc/config.mesh/system
- files/etc/cron.daily/update-clock
- files/usr/local/bin/node-setup
- files/usr/local/bin/restart-services.sh
Bug: Changing the NTP setting in the new UI did nothing. Now it does.
Feature: Add 'continually' mode which is traditional always running NTP. Dont use on nodes with limited RAM.
> Fix NTP problems.

- files/app/main/app.ut
- files/app/partial/status.ut
Mostly to stop people trying to use it when the node is updating or rebooting.
> Put old UI button just on the main page

- patches/747-mikrotik-extra-support.patch
Clock speed inherited from Basebox2 appears to be incorrect. The Basebox2 clock was originally 25 MHz but was changed in 2022 to 40 MHz (see https://github.com/openwrt/openwrt/pull/10990). Assuming this is correct, it does not appear correct for the 5GHz models, so change it back for these.
> Fix clocks on Mikrotik Basebox5 and QRT

- files/app/partial/login.ut
To login we create a cookie and hand it to the browser using AJAX. This cookie is then used to authenticate the browse to the device for all subsequent calls. Chrome and Safari are good with this because the new cookie is in the correct context. Firefox does not like this unless you navigate away from the page and back again (refreshing is insufficient). Quite why isn't clear (it must surely be a bug) but this change works around this problem without impacting other browsers.
> Workaround Firefox cookie caching bug

- files/app/root.ut
HTTP resources are compressed before they're sent. This involves compressing them in the file system (at least until the next OpenWRT merge, where we can avoid this) which, in turn, requires a unique file as the target. We generate this using a random number read from /dev/urandom (we cannot use ucode's random function because requests are served using forked uhttpd instances, which makes it likely we'll get the same random number when serving simultaneous requests). We had assumed this would always work, but perhaps this is not always true. So now, if we cannot generate a unique filename (which we check in the file system before use) we play it safe and dont compress the response.
> Improve when compression is used on http requests

- files/usr/local/bin/mgr/gps.lua
Fix typo of `/dev/nul` instead of `/dev/null` in date command in mgr/gps.lua
Fixes https://github.com/aredn/aredn/issues/1530
> Fix typo of /dev/nul instead of /dev/null

- files/app/root.ut
Preloading too much seems to be causing stability issue.
Reduce to just the essentials for most visitors
> Reduce preloaded code

- files/app/main/status/e/ports-and-xlinks.ut
Modifying uci data while iterating over it was causing memory corruption and at best causing uci values not to be updated, and at worse crashing the uci interpreter and web server. Avoid this by iterating the data we need first, then doing the modifications.
> Fix memory corruption when changing xlinks.

- files/app/partial/changes.ut
Previous had this the other way - reboot displayed regardless - but this makes more sense.
> Only provide reboot option when there are no changes to commit first

- files/usr/local/bin/firstuse-setup
The wifi interface was getting lost during setup, so we make sure it's there.
This is a workaround for an unknown root cause.
> Make sure we definately have wifi setup

- configs/common.config
Create a package to provide the at24 kernel driver, which supports a variety of I2C EEPROMs.
Add support for AT24-compatible I2C Serial EEPROMs, which are often included, for example, on RTC daughterboards.
After:
```
[   54.606884] at24 0-0057: supply vcc not found, using dummy regulator
[   54.614464] at24 0-0057: 4096 byte 24c32 EEPROM, writable, 1 bytes/write
[   54.621598] i2c i2c-0: new_device: Instantiated device 24c32 at 0x57
-rw-------    1 root     root          4096 Sep 17 16:14 /sys/devices/platform/i2c/i2c-0/0-0057/eeprom
```
> Enable kmod-eeprom-at24 package

- files/usr/lib/lua/aredn/services.lua
Some services use various redirects which involve cookies. If we dont include a cookie jar for these tests, they fail when they should pass.
> Include cookies when testing services.

- files/app/root.ut
While there are other mechanisms to prevent you accessing secure pages, it does no harm to block these actions early as an extra security measure.
> Block PUT, POST, DELETE unless logged in or firstboot.

- files/etc/cron.daily/update-clock
- files/etc/hotplug.d/ntp/10-ntp-stratum
When update-clock is run periodically, if ntpd is running continuously, check whether it is actually in sync, as measured by a reported stratum of less than 16.
If it's not in sync, run the full manual clock sync algorithm otherwise used for our periodic-only synchronization.
This should help with hosts that expect to synchronize from an NTP server on the internet, for example, when they've temporarily lost the internet connection. Or alternately, if configured to use a mesh-based NTP server that has disappeared from the mesh.
> Periodically sync time if continuous ntpd is unsynchronized

- files/app/main/status/e/firmware.ut
- files/app/partial/tools.ut
When we use a redirect to force the web browser to download a file after it uses an AJAX request to initiate the operation, htmx looses track of the htmx-request attribute and so doesnt remove it when the operation is done. Work around this by moving the attribute somewhere we dont care about.
> Work around HTMX bug where downloading files doesnt stop the logo spinning

- files/app/main/tools/e/wifiscan.ut
- files/usr/local/bin/node-setup
* Enable VHT support on AC radios. This is experimental and I dont know if it will improve link performance in the real world.
* Switched to 'band' in wireless config as 'hwmode' was deprecated years ago.
* Fixed wifi scanner misreporting connected stations as APs.
> VHT support (experimental)

- files/app/root.ut
- files/usr/share/ucode/aredn/configuration.uc
Avoid any potential race conditions when changing the configuration by putting a lock around any non-GET operations.
> Add locking around operations which change the configuration.

- files/app/main/status/e/firmware.ut
- files/app/main/status/e/packages.ut
New Safari builds no longer support non-integers when setting progress bar values
> Fix progress bars broken on latest Safari builds

- files/app/main/status/e/network.ut
- files/etc/uci-defaults/96_fix_dhcp_dmz
- files/usr/local/bin/aredn_init
Turns out the values we set for the dmz dhcp range was always an incorrect interpretation of the documentation (see https://openwrt.org/docs/guide-user/base-system/dhcp), but the problem was hidden because the netmask would fix it up.
> Fix dmz dhcp values

- files/usr/local/bin/mgr/lqm.lua
On some devices the call to do this was failing. So do it by hand.
> Calculate physical device by hand

- files/app/partial/local-services.ut
Improve which local devices and service we show when logged out or logged in.
Before the devices list was pretty sparse, just showing devices which were public reservations. Now when logged out we only show public reservations which have active leases. When logged in we show all leases and all reservations with additional information if reservations don't have corresponding leases.
For service, when logged out, we no longer show those which cannot be reached. When logged in, these are still visible with additional information indicating this state.
> Improve which local devices and service we show when logged out or logged in.

- files/app/main/status/e/packages.ut
- files/app/partial/general.ut
- files/app/partial/packages.ut
We haven't supported installing packages on low memory node for a few years now, but we will want to provide a mechanism to remove them even with the new UI.
> Allow packages to be removed on low memory nodes.

- files/app/main/inject.ut
- files/app/main/neighbor-device.ut
- files/app/partial/activator.ut
- files/app/partial/local-and-neighbor-devices.ut
- files/app/partial/status.ut
- files/app/resource/css/user.css
Access to extended neighbor info requires lots of extra Javascript and CSS which we dont want to load by default (like
we do when logged in). This provides a very tiny JS shim to load the extra resources but *only* if an attempt is made
to view the neighbor info.
> Provide access to neighbor info without dragging in extra resource unless necessary.

- files/usr/local/bin/mgr/lqm.lua
My continual quest to make nodes which have gone away, but the arp cache insists haven't, actually go away.
> Tweak node detection keepalive

- files/app/partial/changes.ut
When making any sort of network changes, the response to the original commit can just hang until the request times out and we retry it. To improve UI feedback, reduce that timeout and retry the UI update multiple times.
> Speed up commits

- files/app/main/status/e/dhcp.ut
Fixes and tweaks for DHCP option in-browser validation:
- Many options take a list of IP addresses rather than a single address.
- Use <input type="number"> for values that are single integers.
- IP address pairs must be joined by commas, not whitespace.
- Add all the missing patterns.
- Support options that have no value.
- Minor pattern efficiency improvements.
Known issues:
- Styling has not been provided for the numeric input fields.
- Rapid-commit will not work because the --dhcp-rapid-commit option must also be provided.
> Fixes and tweaks for DHCP option in-browser validation

- files/app/main/status/e/dhcp.ut
- files/usr/local/bin/node-setup
More fixes and improvements to DHCP option validation:
- Handle unknown options (defined by number) as text data.
- Always reset to text input when changing to a non-integer data type.
- Tolerate values containing quotation marks.
- Make specifying "vi-encap:" encoding optional for Option 125 because it is the only supported encoding.
- Allow embedded quotation marks in string-encoded vi-encap data.
Known issues:
- Values containing embedded whitespace are not correctly encoded in /var/etc/dnsmasq.conf; each whitespace-separated token appears as a separate dhcp-option line. This problem is also present in both the old and new UI in previous releases.
- Nothing special is done with values that contain embedded quotation marks; these might confuse the dnsmasq option parser.
> More fixes and improvements to DHCP option validation

- files/app/partial/changes.ut
- files/app/root.ut
Tunnel changes, and possibly any network changes, which occur when we're holding a file system lock are making the entire node lockup. Not clear why this would happen, but disable the locking mechanism for now (was recently added as an extra layer of safety when making UI changes).
> Fix unresponsiveness when network changes

- files/app/partial/status.ut
- files/app/resource/css/user.css
For narrow web browser windows, make the layout responsive; 3, 2 and 1 column depending on width.
This is *not* the mobile layout which is somewhat different.
> Make 3 column layour responsive if browser is narrow

- files/app/root.ut
Restrict the range of code where we include locking, and explicitly unlock in case the lock descriptor is being held open elsewhere (somehow).
> Refine PUT/POST locking.

- patches/780-restore-request-class.patch
- patches/series
NOTE. This class is not used by AREDN and is not supported by OpenWRT anymore. This implementation is backported from a much older OpenWRT version. At some point support for this will become difficult. Apps which reply on this should find an alternate approach.
> Restore the Request class used by meshchat.

- files/usr/local/bin/aredn_init
The old configuration allowed the wifi interface to be blank. During an upgrade this caused the channel to reset to the default. The upgrade process now handles and fixes the blank interface and doesn't mess with the channel if already set.
> Fix channel 149 revert bug

- patches/704-dnsmasq-restart.patch
- patches/series
This is a workaround for dnsmasq crashing on supernodes.
Need a proper fix for that still.
> Bump restart timeouts so dnsmasq will respawn if it crashes.

- files/etc/config.mesh/dhcp
- files/usr/local/bin/node-setup
A bug in dnsmasq's rehash function causes memory corruption. Work round this by setting the cache size large enough to avoid triggering it on supernodes which have very large host tables.
> Increase dnsmasq cache sizes for supernodes to avoid memory corruption

- patches/803-experimental-fix-norx-ether.patch
- patches/series
Experimental fix to avoid occasions when the ethernet controller doesnt start up.
The old driver used 'at803x-override-sgmii-link-check' to work around a bug where an ethernet link wouldnt start after it has been auto-negotiated. This flag no longer does anything as this patch was deprecated as the linux driver has been rewritten. There is a bug, possibly the same bug as its related to the same startup case, where if the chips goes to sleep it doesnt not then correct wakeup the RX ethernet MAC. That certainly is the sympton we see where everything works but no RX traffic is ever received.
Unfortunately there is no way to force the condition to happen, so we dont know if this will fix it until we're sure we dont see the issue anymore.
NOTE. Not to be confused with any other problems with …
> Experimental fix to avoid occasions when the ethernet controller doesnt start up

- files/usr/local/bin/node-setup
- files/usr/local/bin/restart-services.sh
Tunnel devices can get reassigned when tunnel configuration changes so restart LQM otherwise it can get out of sync.
> Restart lqm when tunnel configuration changes.

- files/etc/config.mesh/dhcp
- files/usr/local/bin/node-setup
This change was made while debugging poor dnsmasq behavior. No longer necessary.
> Revert explicitly setting of dnsmasq cache size

- files/www/cgi-bin/ping
- files/www/cgi-bin/traceroute
Previously we forced these commands to use the dtdlink ip address as their source. However if this interface isn't actually up then this will fail. Instead let these command pick the best interface for them.
> Allow and ping and traceroute to auto select the best interface

- files/app/main/status/e/network.ut
The layout of LAN type looked different on different browsers due to CSS incpompatibilies. Tweaked to be the same.
> Fix layout of LAN type so it looks the same on all browsers

- patches/731-ag71xx-updates-and-fixes.patch
There was an old rocket 5ac patch in previous kernels what help the network work at full speed. Experiment with bringing it into this kernel to see if it fixes what may be ethernet issue with some rocket 5ac lite hardware.
Experimental.
> Older patch for Rocket 5AC Lite dts

- files/etc/config.mesh/firewall
This port goes straight to OLSR and has a habit of crashing it causing mesh instability.
Access to this data is provided via the sysinfo.json api.
> We no longer allow access to port 9090 from the mesh.

- files/usr/local/bin/mgr/lqm.lua
Doesn't make anything faster. It's a more accurate lie.
> Fix tx/rx bit rate reporting which was 1/2 what it should be.

- files/app/main/status/e/radio-and-antenna.ut
- files/app/main/tools/e/wifiscan.ut
- files/app/partial/radio-and-antenna.ut
- files/app/partial/tools.ut
- files/app/resource/css/admin.css
- files/usr/local/bin/mgr/lqm.lua
- files/usr/local/bin/node-setup
- files/usr/share/ucode/aredn/radios.uc
Allow to mesh node radios to be configured to *only* exchange data with each other.
> Add Mesh PtP mode (like of Mesh PtMP mode)

- files/etc/config.mesh/dhcp
- files/usr/local/bin/node-setup
- patches/704-dnsmasq-mimalloc.patch
- patches/series
dnsmasq is a pathological memory allocator/freer and the malloc/free implementation used in OpenWRT (from the library musl libc) is known to be poor. I'd perviously observed its performance to be very bad, but its ability to handle memory fragmentation is also known to be bad.
So, for this app I'm switching out the standard allocator for an alternative called "mimalloc" (https://microsoft.github.io/mimalloc/) which has much better performance. Let's see if this resolve this problem.
> Replace the malloc/free functions for dnsmasq

- files/etc/hotplug.d/iface/01-wifi-fixup
For yet unknown reasons, the ipv4 wifi address can go missing when a node starts up. Until the root cause is determined, this script will make sure it is set.
> Fixup the wifi address when missing

- files/etc/sysctl.d/01-vm.conf
- patches/781-disable-lru-gen.patch
- patches/series
On low memory devices (<=32M) min_free_kbytes is set to 1M. On larger devices it is set to 16M. This is the memory the kernel keeps around for situations where it absolutely needs memory now or with crash. AREDN nodes are relatively stable memory wise, and this high limit is effectively reducing the memory we actually have to do work. So make it lower to improve stability.
> Lower min_free_kbytes to 1M (from default of 16M)

- files/app/partial/dialog-footer.ut
If the dialog closed before any pending response was received from the node, it was discarded so the commit/revert banner might not appeared.
> Fix dialog close race condition

- files/app/main/status/e/radio-and-antenna.ut
- files/usr/local/bin/mgr/lqm.lua
AC nodes cannot auto distance, and sometimes this is important.
> Improve babel/lqm interaction when starting up ac nodes

- patches/010-lz77-decompression-fix.patch
- patches/series
OpenWRT almost got it right, but made one bad assumption about what some devices need compared to the original code which didnt.
> Refix the LZ77 decompression for Mikrotik

- files/app/main/status/e/firmware.ut
When we fail to download the firmware configuration, attempt to ping the download host to see if it's reachable, and report if not. Hopefully helps debugging download issues.
> When we fail to download firmware, ping to host to see if its reachable

- files/app/partial/mesh-datab.ut
- files/app/partial/mesh.ut
- files/app/partial/meshb.ut
- files/app/resource/css/user.css
- files/app/resource/js/meshpage.js
- files/usr/local/bin/node-setup
OLSR used ETX as a measurement of distance/availability for nodes and services. Babel doesnt do this because it uses different mechanisms for different link types when determining routing. All this information is reduced to a routing metric; the larger the more distance a resource is. We use this to order resources and include that information in the page.
Work in progress as we dont have a good handle comparing large this metric is and how likely and fast we can access a resource.
> Babel Mesh Page: Improve grouping

- files/usr/local/bin/mgr/wireless_monitor.lua
The wireless monitor uses wifi scans to repair broken networks, but if the node is managed (not adhoc) this seems to actually break operational connections. So disable this feature in non-adhoc modes.
> Only run wireless monitor in adhoc mode.

- files/app/main/tools/e/wifiscan.ut
- files/app/partial/tools.ut
It breaks some connections and requires a reboot to repair them.
> Disable wifi scan option for some mesh modes.

- files/usr/share/ucode/aredn/messages.uc
Legacy tunnels cannot support Babel, so add a TODO item on a node still using them encouraging the owner to migrate to Wireguard.
> Add a TODO to migrate legacy tunnels

- files/app/main/status/e/tunnels.ut
Legacy tunnels cannot support Babel, so while we still support them, prevent people making new ones.
> Dont allow new legacy tunnels

- patches/703-disable-ipv6-dnsmasq.patch
AREDN doesnt use IPv6 addresses, and so forwarding AAAA DNS requests upstream can fail if the upstream doesn't handle them correctly. As we don't want these responses anyway, dont forward them and return an NOERROR response to the requester.
NOTES:
DNS clients should issue A and AAAA requests in parallel, but in reality many issue AAAA, wait for a response, then send an A request. If the AAAA response never arrives we end up with a delay until the client times out. This default timeout for many clients is 5 seconds. AREDN correctly handles AAAA so the lost responses are probably due to some upstream issues.
This *might* be why some people are seeing DNS delays on AREDN and some don't.
> Do not forward AAAA requests upstream

- files/app/main/status/e/radio-and-antenna.ut
hostapd is necessary for non mesh wifi modes. If this isn't found (on tiny builds unless the package is explicitly installed) then dont offer the modes.
> Dont support some wifi modes on tiny builds

- files/usr/share/ucode/aredn/configuration.uc
Backup included files from /etc/config which are just overwritten by files in /etc/config.mesh. It was harmless to include them but also pointless.
> Fix exclusion of files in backup which are unnecessary.

- files/etc/cron.hourly/check-supernodes
When a supernode had been detected we setup DNS forwarding for local.mesh so we could find unknown names. Now if the supernode isn't detected we setup a null forward (ie. there isn't one) so we dont send these lookups to the standard upstream DNS server which wont know anything about local.mesh
> Improve supernode detector for when there isn't a supernode.

- files/etc/config.mesh/uhttpd
Still works on Tiny devices which dont have ipv6 link local devices.
> Make webserver available on ipv6 link local address

- files/etc/cron.hourly/check-services
To keep compatibility between old OLSR only nodes, hybrid OLSR+Babel nodes, and future Babel-only nodes, we need to advertise the supenode IP carefully so older code doesnt break while newer code will work and hybrid code tolerates both.
> Keep supernode name out of OLSR but in Arednlink.

- files/usr/local/bin/restart-services.sh
Babel is restarted when the network is reconfigured. This can involved wireguard devices being reassigned to new connections and new address. This will confuse arednlink so just restart it (for the same reasons we restart babel).
> Restart arednlink when we restart babel.

- files/app/main/status/e/ports-and-xlinks.ut
- files/usr/local/bin/node-setup
DNS servers are only made available on active networks. The default network had been "lan" but on some radios there might only be power. So move them to the "wifi" network, which is *always* up.
> Move DNS servers to the "wifi" network (wlanX or br-nomesh) so they're always active.

- files/usr/local/bin/node-setup
node-setup was re-written for a post-lua world. Mistakes were made. Here's another - the tunnel endpoint was missing for tunnel clients so no traffic could be forwarded over these connections. Fixed.
> Missing tunnel endpoint when setting up firewall

- files/app/partial/local-and-neighbor-devices.ut
Which is all nodes, but different ips can get resolved under different situations, so try to deal with all that.
Babel-only does this all differently anyway.
> Improve handling of nodes with multiple names and ip addresses.

- files/etc/mesh-release
- files/usr/local/bin/aredn_init
dtdmac was often set to 0.0.0 which is both not random and wrong.
> Fix generation of dtdmac

- patches/790-morsemicro-support.patch
This will make the device name find the correct firmware in the online firmware tool.
> Make the Heltec HT-HD01 an alt name for the MorseMicro EKH03

- files/etc/arednsysupgrade.conf
- files/usr/share/ucode/aredn/configuration.uc
We added /etc/config file into the backup in an attempt to speed up the update process by reducing the number of reboots. However, this rarely works as there's always some change during an update which makes the second reboot necessary. So, remove the /etc/config files as they serve no purpose.
> Reduce the files we keep in the backups.

- files/app/main/status/e/firmware.ut
The firmware refresh button will now autoselect the next firmware to upgrade with. It will select the next release, nightly, or babel mighty depending on what series the device is using. It will not select a firmware if there is nothing new.
> Automatically select the best firmware to upgrade to.

- files/usr/local/bin/node-setup
Babel doesnt use peer addresses for xlinks broadcasts, so this bring OLSR inline with it to simplify migration.
> Use broadcast address in all xlink olsr payloads.

- files/etc/uci-defaults/94_fix_bad_dtdlink
This happened with early babel builds so fix them up when we find them. This should be removed before release.
> Temporary fixup for nodes with bad dtdlink addresses.

- files/etc/uci-defaults/21_wifi_options
The Old UI would sometimes disable the mesh wifi be remove the wifi_intf value rather than setting wifi_enable to non-zero. Handle this case during migration.
> Fix wifi migration from Old UI.

- files/etc/uci-defaults/21_wifi_options
The Old UI would sometimes disable the wifi mesh by setting the wifi_intf property to "" rather than setting the wifi_enable property to non-null. Handle this case.
> Handle Old UI wifi migration.

- files/app/partial/network.ut
- files/usr/local/bin/node-setup
If the node was wifi-only (no network cable attached) then DNS would not come up correctly and non-AREDN names didnt resolve. Fix this by moving the dns names onto the wifi network (which is always up, even if we're using br-nomesh).
Already fixed in Babel version.
> Make sure DNS is always active on the node.

- patches/714-disable-wpa-supplicant.patch
We previous disable wpa_supplicant for PTxP modes to save memory as we dont use encryption.  However, stations still need it running to function so we cannot disable it for them. We can disable hostapd for stations so do that to save memory
> PTxP fixes for what memory saving broke.

- files/app/main/neighbor-device.ut
- files/app/partial/network.ut
- files/usr/local/bin/mgr/lqm.uc
- files/usr/local/bin/node-setup
- files/usr/share/ucode/aredn/configuration.uc
Restore user ability to block specific neighbor connections on a node. This was available in meshap mode, but is now generally available again by using babel to deny incoming routes from specified neighbors.
> Restore user blocks for all mesh types.

- files/usr/share/ucode/aredn/configuration.uc
This was breaking the command line supportdata tool
> Change check for adhoc mode to avoid circular dependency

- configs/ramips-mt7621-morse.config
Reverts aredn/aredn#2381
ffmpeg generates assembly language incompatible with the target processor. Revert this until OpenWRT updates their ffmpeg implementation.
> Revert "Add video proxy packags to MorseMicro HaLowLink 1"

- files/usr/local/bin/mgr/babel_monitor.uc
- files/usr/share/ucode/aredn/babel.uc
On rare occasions Babel wil fail to sync with some of its neighbors. It hears them but refuses to get a cost metric from them. This means the local route has a metric of -1, which means unreachable. No matter how long we wait the problem never resolves itself (or takes so long we've never seen it resolve).
As we dont know how to reproduce this bug, here we will try to detect it and restart babel, without saving state, to fix the issue.
Bandaid solution.
> Monitor Babel and restart if necessary.

- files/etc/sysctl.d/02-panic-on-oom.conf
Currently the Linux default is to kill random things when we run out of memory. This tends to result in partially working, partially broken nodes. Better to just reboot.
> Panic and reboot if we run out of memory

- patches/714-disable-wpa-supplicant.patch
Mostly this is to save memory by not running large daemons when we dont need them.
> Improve selection of hostapd and wpa_supplicant

- patches/714-disable-wpa-supplicant.patch
Despite what the documenation claims, you still need to run wpa_supplicant for stations even with open security.
> Make sure to run wpa_supplicant for open stations.

- files/usr/local/bin/mgr/babel_monitor.lua
Link local ping is doing most of the protection work here, so LQ can be lower.
> Drop babel monitor LQ requirement to 50%

- files/usr/share/ucode/aredn/hardware.uc
Sometimes, particularly after an upgrade, the Halow radio doesnt restart correctly. Make sure the UI handles this.
> Halow radios sometimes dont restart correctly. Make UI handle this.
